### ISSUE TITLE
Image rendered without legend

### ISSUE THREAD

**Issue by Quicksy** [grafana/grafana-image-renderer#100]
I've installed image renderer into the separate Docker container using docker compose with grafana 6.6.0
**What happened**: 
Images in notifications contains only graph itself, the legend that supposed to be on the right side of the graph is not on this notification.

**What you expected to happen**:
Get image with graph and the legend for this graph on it.

**Environment**:
- Grafana Image Renderer version: latest
- Grafana version: 6.6.0
- Installed plugin or remote renderer service: Remote renderer in docker;

**Comment by Quicksy** [comment]
Well, it got fixed with grafana's update to 6.6.1. 
This is the link to the issue in the grafana's github: https://github.com/grafana/grafana/issues/21830

**Comment by marefr** [comment]
Thanks. Sorry, forgot to update this issue.
