### ISSUE TITLE
Why I actual use has not imageUrl in webhook?

### ISSUE THREAD

**Issue by linhuisheng** [grafana/grafana-image-renderer#101]
![2](https://user-images.githubusercontent.com/8087304/74342063-d41ff300-4de3-11ea-8c54-ec9e6bbad806.png)
Send Test flask server has imageUrl,:
{'dashboardId': 1, 'evalMatches': [{'value': 100, 'metric': 'High value', 'tags': None}, {'value': 200, 'metric': 'Higher Value', 'tags': None}], 'imageUrl': 'https://grafana.com/assets/img/blog/mixed_styles.png', 'message': 'Someone is testing the alert notification within grafana.', 'orgId': 0, 'panelId': 1, 'ruleId': 0, 'ruleName': 'Test notification', 'ruleUrl': 'http://localhost:3000/', 'state': 'alerting', 'tags': {}, 'title': '[Alerting] Test notification'}

But actual use has not imageUrl in webhook?
{'dashboardId': 1, 'evalMatches': [{'value': 50.80555555555556, 'metric': '192.168.1.107', 'tags': {'cluster_name': 'testc', 'dc_name': 'testv', 'host_name': '192.168.1.107', 'instance': '192.168.1.105', 'job': 'vmware_vcenter'}}], 'message': '{{host}}', 'orgId': 1, 'panelId': 2, 'ruleId': 1, 'ruleName': 'Host CPU usage alert', 'ruleUrl': 'http://localhost:3000/d/X7YekC8Zk/exsi-dashboard?fullscreen&edit&tab=alert&panelId=2&orgId=1', 'state': 'alerting', 'tags': {}, 'title': '[Alerting] Host CPU usage alert'}

**Comment by linhuisheng** [comment]
I'm working normally grafana-image-renderer:

![4](https://user-images.githubusercontent.com/8087304/74342625-be5efd80-4de4-11ea-9815-e0d252c633a4.png)

but has not renderer url to send webhook server ,how to get url to send to webhook server?
{'dashboardId': 1, 'evalMatches': [{'value': 46.58333333333333, 'metric': '192.168.1.107', 'tags': {'cluster_name': 'testc', 'dc_name': 'testv', 'host_name': '192.168.1.107', 'instance': '192.168.1.105', 'job': 'vmware_vcenter'}}], 'message': '{{host}}', 'orgId': 1, 'panelId': 2, 'ruleId': 1, 'ruleName': 'Host CPU usage alert', 'ruleUrl': 'http://localhost:3000/d/X7YekC8Zk/exsi-dashboard?fullscreen&edit&tab=alert&panelId=2&orgId=1', 'state': 'alerting', 'tags': {}, 'title': '[Alerting] Host CPU usage alert'}

**Comment by linhuisheng** [comment]
I'm working normally grafana-image-renderer:

![4](https://user-images.githubusercontent.com/8087304/74342625-be5efd80-4de4-11ea-9815-e0d252c633a4.png)

but has not renderer url to send webhook server ,how to get url to send to webhook server?
{'dashboardId': 1, 'evalMatches': [{'value': 46.58333333333333, 'metric': '192.168.1.107', 'tags': {'cluster_name': 'testc', 'dc_name': 'testv', 'host_name': '192.168.1.107', 'instance': '192.168.1.105', 'job': 'vmware_vcenter'}}], 'message': '{{host}}', 'orgId': 1, 'panelId': 2, 'ruleId': 1, 'ruleName': 'Host CPU usage alert', 'ruleUrl': 'http://localhost:3000/d/X7YekC8Zk/exsi-dashboard?fullscreen&edit&tab=alert&panelId=2&orgId=1', 'state': 'alerting', 'tags': {}, 'title': '[Alerting] Host CPU usage alert'}

**Comment by marefr** [comment]
Looking here images are supported when you have setup external image storage like S3 or GCS: https://grafana.com/docs/grafana/latest/alerting/notifications/#all-supported-notifiers. For details here: https://grafana.com/docs/grafana/latest/alerting/notifications/#external-image-store

**Comment by marefr** [comment]
Closing this because this is more of a question and also not related to image renderer plugin.
