### ISSUE TITLE
Unable to start Grafana (Windows) with version 1.0.8 and 1.0.9

### ISSUE THREAD

**Issue by mw-solutions** [grafana/grafana-image-renderer#102]
After having installed the grafana-image-renderer plugin through the commandline tool, Grafana is not more able to start. It starts with version 1.0.7. I tried several times with 1.0.8 and now with v1.0.9 but it always fails with following messages in the console log:

[32mINFO[0m[02-13|21:02:25] HTTP Server Listen                       [32mlogger[0m=http.server [32maddress[0m=[::]:3000 [32mprotocol[0m=http [32msubUrl[0m= [32msocket[0m=
[31mEROR[0m[02-13|21:02:26] Stopped RenderingService                 [31mlogger[0m=server [31mreason[0m="Failed to start renderer plugin: Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to be recompiled to support the latest protocol."
[32mINFO[0m[02-13|21:02:26] Stopped PluginManager                    [32mlogger[0m=server [32mreason[0m="context canceled"
[32mINFO[0m[02-13|21:02:26] Stopped NotificationService              [32mlogger[0m=server [32mreason[0m="context canceled"
[32mINFO[0m[02-13|21:02:26] Stopped provisioningServiceImpl          [32mlogger[0m=server [32mreason[0m="context canceled"
[32mINFO[0m[02-13|21:02:26] Stopped UsageStatsService                [32mlogger[0m=server [32mreason[0m="context canceled"
[32mINFO[0m[02-13|21:02:26] Stopped UserAuthTokenService             [32mlogger[0m=server [32mreason[0m="context canceled"
[32mINFO[0m[02-13|21:02:26] Stopped InternalMetricsService           [32mlogger[0m=server [32mreason[0m="context canceled"
[32mINFO[0m[02-13|21:02:26] Stopped BackendPluginManager             [32mlogger[0m=server [32mreason[0m="context canceled"
[33mWARN[0m[02-13|21:02:26] plugin failed to exit gracefully         [33mlogger[0m=plugins.backend [33mpluginId[0m=grafana-image-renderer
[32mINFO[0m[02-13|21:02:26] Stopped AlertEngine                      [32mlogger[0m=server [32mreason[0m="context canceled"
[32mINFO[0m[02-13|21:02:26] Stopped RemoteCache                      [32mlogger[0m=server [32mreason[0m="context canceled"
[32mINFO[0m[02-13|21:02:26] Stopped CleanUpService                   [32mlogger[0m=server [32mreason[0m="context canceled"
[32mINFO[0m[02-13|21:02:26] Stopped Stream Manager
[31mEROR[0m[02-13|21:02:26] A service failed                         [31mlogger[0m=server [31merr[0m="Failed to start renderer plugin: Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to be recompiled to support the latest protocol."
[31mEROR[0m[02-13|21:02:26] Server shutdown                          [31mlogger[0m=server [31mreason[0m="Failed to start renderer plugin: Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to be recompiled to support the latest protocol."

After having deleted the grafana-image-renderer plugin directory every works again. And restoring a backup of the 1.0.7 directory everything works too.
I use Windows 10 Pro and Enterprise.

**Comment by marefr** [comment]
Thanks. Going to investigate why this happens.
