### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by reuvygroovy** [grafana/grafana-image-renderer#108]
Hi,

When trying to download the newest version of the plugin 1.0.10 from the grafana cli it doesn't work, When trying to download it manually from this link https://grafana.com/api/plugins/grafana-image-renderer/versions/1.0.10/download we get the following:

{
  "code": "BadRequest",
  "message": "Version 1.0.10 is not available for undefined-undefined"
}

**Comment by marefr** [comment]
Please use the bug report template https://github.com/grafana/grafana-image-renderer/issues/new?labels=type%3A+bug&template=1-bug_report.md

Regarding downloading manually it's a known issue #47

**Comment by marefr** [comment]
#47 is now closed and for not being able to install using cli sounds like similar problem as #112 so will close this.
