### ISSUE TITLE
Timeout error with remote rendering

### ISSUE THREAD

**Issue by Karan96Kaushik** [grafana/grafana-image-renderer#109]
**What happened**:
Receiving Timeout error while rendering complete dashboard using "/render/dashboard/db" method and grafana-image-renderer with remote server on localhost

**What you expected to happen**:
Receive a PNG snapshot of the complete dashboard

**How to reproduce it (as minimally and precisely as possible)**:
1. Change grafana config for remote rendering
2. Run grafana
3. Open dashboard with a small time range ( < 1 Day)
4. Change URL adding /render/dashboard/db after host and before dashboard parameters to render the image
5. Wait

**Anything else we need to know?**:
Also, I don't see an option to render image for the complete dashboard in Share option
![Screenshot from 2020-02-27 13-17-50](https://user-images.githubusercontent.com/44289074/75422907-9aaec200-5963-11ea-97e8-a5a354666e07.png)
 but I have the option to render individual panels which works.

**Environment**:
- Grafana Image Renderer version: 1.0.10
- Grafana version: 6.6.1
- Installed plugin or remote renderer service: remote renderer service
- OS Grafana Image Renderer is installed on: Ubuntu 18
- User OS & Browser: Ubuntu Firefox
- Others:

Grafana Log:

INFO[02-27|13:02:09] Rendering                                logger=rendering renderer=http path="dashboard/db/d/o8OgaALWk/battery-pack-and-cell-measurements?orgId=2&from=1581445800000&to=1581618599000"
EROR[02-27|13:03:11] Failed to send request to remote rendering service. logger=rendering renderer=http error="Get http://localhost:8081/render?domain=localhost&encoding=&height=400&renderKey=RnghkbWqMEb3r1XAkZ1ThDUhmqhbaxmh&timeout=60&timezone=&url=http%3A%2F%2Flocalhost%3A3000%2Fdashboard%2Fdb%2Fd%2Fo8OgaALWk%2Fbattery-pack-and-cell-measurements%3ForgId%3D2%26from%3D1581445800000%26to%3D1581618599000%26render%3D1&width=800: context deadline exceeded"
EROR[02-27|13:03:11] Rendering failed.                        logger=context userId=1 orgId=2 uname=admin error="Failed to send request to remote rendering service. Get http://localhost:8081/render?domain=localhost&encoding=&height=400&renderKey=RnghkbWqMEb3r1XAkZ1ThDUhmqhbaxmh&timeout=60&timezone=&url=http%3A%2F%2Flocalhost%3A3000%2Fdashboard%2Fdb%2Fd%2Fo8OgaALWk%2Fbattery-pack-and-cell-measurements%3ForgId%3D2%26from%3D1581445800000%26to%3D1581618599000%26render%3D1&width=800: context deadline exceeded"
EROR[02-27|13:03:11] Request Completed                        logger=context userId=1 orgId=2 uname=admin method=GET path=/render/dashboard/db/d/o8OgaALWk/battery-pack-and-cell-measurements status=500 remote_addr=192.168.0.197 time_ms=62054 size=1722 referer=

image renderer server log:

{"url":"/render?domain=localhost&encoding=&height=400&renderKey=uIXsTHStxH4yo7sceSPXTIO1S3OI1MQ9&timeout=60&timezone=&url=http%3A%2F%2Flocalhost%3A3000%2Fdashboard%2Fdb%2Fd%2Fo8OgaALWk%2Fbattery-pack-and-cell-measurements%3ForgId%3D2%26from%3D1581445800000%26to%3D1581791399000%26render%3D1&width=800:","stack":"TimeoutError: waiting for function failed: timeout 60000ms exceeded\n    at new WaitTask (/home/karansgs/Documents/githubWorkSpace/grafana-image-renderer/node_modules/puppeteer/lib/DOMWorld.js:549:28)\n    at DOMWorld.waitForFunction (/home/karansgs/Documents/githubWorkSpace/grafana-image-renderer/node_modules/puppeteer/lib/DOMWorld.js:454:12)\n    at Frame.waitForFunction (/home/karansgs/Documents/githubWorkSpace/grafana-image-renderer/node_modules/puppeteer/lib/FrameManager.js:657:28)\n    at Page.waitForFunction (/home/karansgs/Documents/githubWorkSpace/grafana-image-renderer/node_modules/puppeteer/lib/Page.js:1144:29)\n    at Browser.<anonymous> (/home/karansgs/Documents/githubWorkSpace/grafana-image-renderer/build/browser/browser.js:158:28)\n    at Generator.next (<anonymous>)\n    at /home/karansgs/Documents/githubWorkSpace/grafana-image-renderer/build/browser/browser.js:7:71\n    at new Promise (<anonymous>)\n    at __awaiter (/home/karansgs/Documents/githubWorkSpace/grafana-image-renderer/build/browser/browser.js:3:12)\n    at /home/karansgs/Documents/githubWorkSpace/grafana-image-renderer/build/browser/browser.js:156:53","level":"error","message":"Request failed"}
{"message":"::ffff:127.0.0.1 - - [27/Feb/2020:06:42:36 +0000] \"GET /render?domain=localhost&encoding=&height=400&renderKey=uIXsTHStxH4yo7sceSPXTIO1S3OI1MQ9&timeout=60&timezone=&url=http%3A%2F%2Flocalhost%3A3000%2Fdashboard%2Fdb%2Fd%2Fo8OgaALWk%2Fbattery-pack-and-cell-measurements%3ForgId%3D2%26from%3D1581445800000%26to%3D1581791399000%26render%3D1&width=800: HTTP/1.1\" 500 96 \"-\" \"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0\"\n","level":"error"}
{"url":"/render?domain=localhost&encoding=&height=400&renderKey=RnghkbWqMEb3r1XAkZ1ThDUhmqhbaxmh&timeout=60&timezone=&url=http%3A%2F%2Flocalhost%3A3000%2Fdashboard%2Fdb%2Fd%2Fo8OgaALWk%2Fbattery-pack-and-cell-measurements%3ForgId%3D2%26from%3D1581445800000%26to%3D1581618599000%26render%3D1&width=800","stack":"TimeoutError: waiting for function failed: timeout 60000ms exceeded\n    at new WaitTask (/home/karansgs/Documents/githubWorkSpace/grafana-image-renderer/node_modules/puppeteer/lib/DOMWorld.js:549:28)\n    at DOMWorld.waitForFunction (/home/karansgs/Documents/githubWorkSpace/grafana-image-renderer/node_modules/puppeteer/lib/DOMWorld.js:454:12)\n    at Frame.waitForFunction (/home/karansgs/Documents/githubWorkSpace/grafana-image-renderer/node_modules/puppeteer/lib/FrameManager.js:657:28)\n    at Page.waitForFunction (/home/karansgs/Documents/githubWorkSpace/grafana-image-renderer/node_modules/puppeteer/lib/Page.js:1144:29)\n    at Browser.<anonymous> (/home/karansgs/Documents/githubWorkSpace/grafana-image-renderer/build/browser/browser.js:158:28)\n    at Generator.next (<anonymous>)\n    at /home/karansgs/Documents/githubWorkSpace/grafana-image-renderer/build/browser/browser.js:7:71\n    at new Promise (<anonymous>)\n    at __awaiter (/home/karansgs/Documents/githubWorkSpace/grafana-image-renderer/build/browser/browser.js:3:12)\n    at /home/karansgs/Documents/githubWorkSpace/grafana-image-renderer/build/browser/browser.js:156:53","level":"error","message":"Request failed"}

**Comment by marefr** [comment]
First, support for rendering a full dashboard is experimental. The URL you're using doesn't look correct, should be `/render/d/<uid>`
