### ISSUE TITLE
malformed HTTP status code

### ISSUE THREAD

**Issue by negbie** [grafana/grafana-image-renderer#11]
Hi,

am I doing something wrong? Build and run it:
node app.js
1|1|tcp|0.0.0.0:50059|grpc
Renderer plugin started

Used direct link in Grafana and saw this in log:

t=2019-01-20T22:19:24+0100 lvl=eror msg="Failed to send request to remote rendering service." logger=rendering error="Get http://localhost:50059/render?domain=localhost&encoding=&height=500&renderKey=Ssd8i2Z5ryppUtjMeclxsIAsDMDoA8j2&timeout=60&timezone=Europe%2FBerlin&url=http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2FC95vOQwmk%2Fnew-dashboard-copy%3ForgId%3D1%26panelId%3D2%26from%3D1547997538516%26to%3D1548019138516%26width%3D1000%26height%3D500%26tz%3DEurope%252FBerlin%26render%3D1&width=1000: net/http: HTTP/1.x transport connection broken: malformed HTTP status code \"\\x00\\xfe\\x03\\x00\\x00\\x00\\x01\\x00\\x00\\x04\\b\\x00\\x00\\x00\\x00\\x00\\x00?\\x00\\x01\\x00\\x00\\b\\x06\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\""

t=2019-01-20T22:19:24+0100 lvl=eror msg="Rendering failed." logger=context userId=1 orgId=1 uname=admin error="Failed to send request to remote rendering service. Get http://localhost:50059/render?domain=localhost&encoding=&height=500&renderKey=Ssd8i2Z5ryppUtjMeclxsIAsDMDoA8j2&timeout=60&timezone=Europe%2FBerlin&url=http%3A%2F%2Flocalhost%3A3000%2Fd-solo%2FC95vOQwmk%2Fnew-dashboard-copy%3ForgId%3D1%26panelId%3D2%26from%3D1547997538516%26to%3D1548019138516%26width%3D1000%26height%3D500%26tz%3DEurope%252FBerlin%26render%3D1&width=1000: net/http: HTTP/1.x transport connection broken: malformed HTTP status code \"\\x00\\xfe\\x03\\x00\\x00\\x00\\x01\\x00\\x00\\x04\\b\\x00\\x00\\x00\\x00\\x00\\x00?\\x00\\x01\\x00\\x00\\b\\x06\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\""

t=2019-01-20T22:19:24+0100 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/render/d-solo/C95vOQwmk/new-dashboard-copy status=500 remote_addr=[::1] time_ms=1 size=1722 referer="http://localhost:3000/d/C95vOQwmk/new-dashboard-copy?orgId=1"

**Comment by negbie** [comment]
My bad. I did not run it as server and forget to use the port right port flag.

**Comment by rmeichsner** [comment]
Hi,

could you solve the issue? We have the same problems to get the grafana-image-renderer Plugin working.

Manually executing plugin_start_linux_amd64 brings this Output:
/var/lib/grafana/plugins/grafana-image-renderer/plugin_start_linux_amd64
1|1|tcp|127.0.0.1:50059|grpc
Renderer plugin started

An automated starting from Grafana doesn't work.

Nevertheless even pointing rendering url to hostname:50059/render doesn't work.

Any suggestions?

Thanks in advance,
Ruben
