### ISSUE TITLE
Image render shows popup description without disable popup option

### ISSUE THREAD

**Issue by xenon007** [grafana/grafana-image-renderer#111]
**What happened**:
Images redered with Description bubble like on the image
<img src="http://x07.su/uploads/afa74179-6480-4573-9993-545ea468d093.jpg">
**What you expected to happen**:
Rendered image without bubble (by default option) and ENV settings trigger like _GF_RENDER_DESCRIPTION_BUBBLES=true/false_
**How to reproduce it (as minimally and precisely as possible)**:
Setup description on any panel and render it
**Anything else we need to know?**:
We are use curl for renders without UI

**Environment**:
- Grafana Image Renderer version: 1.0.9 (docker)
- Grafana version: 6.5.3
- Installed plugin or remote renderer service: natel-discrete-pane , natel-influx-admin-panel, grafana-piechart-panel, vonage-status-panel, camptocamp-prometheus-alertmanager-datasource, grafana-clock-panel and remote render in docker
- OS Grafana Image Renderer is installed on: SLES 12,15, RHEL 7, OEL 7
- User OS & Browser: Win10, Latest Chrome
- Others: none

**Comment by marefr** [comment]
Thanks. That definitely looks like a bug and an environment for hiding them shouldn't be needed.
