### ISSUE TITLE
Domain parameter not respected in render request

### ISSUE THREAD

**Issue by joemillerr** [grafana/grafana-image-renderer#113]
**What happened**:
`Failed to send request to remote rendering service." logger=rendering renderer=http error="Get https://grafana-image-renderer.mydomain.com/render?domain=grafana.mydomain.com&encoding=&height=500&renderKey=34gujAluZNGg4YZEoZGtixvRBA2Oqv2u&timeout=30&timezone=&url=https%3A%2F%2Fgrafana.mydomain.com%2Fd-solo%2FwP1oU4lZk%2Falert-test%3ForgId%3D1%26panelId%3D2%26render%3D1&width=1000: context deadline exceeded"`

**What you expected to happen**:
`/render?domain=mydomain.com`

**How to reproduce it (as minimally and precisely as possible)**:
I have the image renderer running in a Docker container separate from Grafana.  They are both on the same domain. The request above works in a browser when I remove the hostname from the domain parameter.  I have both the server and rendering blocks set with specific domain that the request doesn't seem to be respecting since it has the FQDN of my grafana instance in the domain param.

Relevant INI configs:

```
[server]
domain = mydomain.com
root_url = https://grafana.mydomain.com
[log]
level = debug
mode = console
filters = rendering:debug
[auth]
org_name = Main Org.
org_role = Viewer
[auth.anonymous]
enabled = true
[auth.ldap]
enabled = true
[alerting]
notification_timeout_seconds = 60
[rendering]
server_url = https://grafana-image-renderer.mydomain.com/render
callback_url = https://grafana.mydomain.com/
domain = mydomain.com
```

**Anything else we need to know?**:
I'm using SSL but have the renderer set to ignore .

**Environment**:
- Grafana Image Renderer version: 1.0.10
- Grafana version: 6.6.2
- Installed plugin or remote renderer service:
- OS Grafana Image Renderer is installed on: Docker Hub Latest

**Comment by joemillerr** [comment]
Any ideas? 

@marefr

**Comment by marefr** [comment]
@joemillerr seems like Grafana cannot connect to https://grafana-image-renderer.mydomain.com/render

**Comment by marefr** [comment]
Seems like a configuration error so will close this. Will consider reopen if you can provide information showing this is a grafana/grafana image render problem

**Comment by joemillerr** [comment]
@marefr I cannot view the render either using that URL in the error log but if I remove the hostname and use the actual domain for the "domain" param the render appears just fine.  As far as I can tell the "domain" param isn't being effected by any configuration I can find documentation for.  I apologize if this was unclear.

**Comment by marefr** [comment]
Not sure I understand. The problem here is that Grafana cannot communicate with the renderer using your configured server_url In rendering section. That means that configured domain under server section doesn't matter until the request from Grafana actually reaches rendering service.

**Comment by joemillerr** [comment]
If I update the URL that errors out from ```https://grafana-image-renderer.mydomain.com/render?domain=grafana.mydomain.com&encoding=&height=500&renderKey=34gujAluZNGg4YZEoZGtixvRBA2Oqv2u&timeout=30&timezone=&url=https%3A%2F%2Fgrafana.mydomain.com%2Fd-solo%2FwP1oU4lZk%2Falert-test%3ForgId%3D1%26panelId%3D2%26render%3D1&width=1000```

And I change `domain=grafana.mydomain.com` to `domain=mydomain.com` the render loads.

**Comment by marefr** [comment]
I see. The domain parameter provided to renderer is solely used for setting the domain of cookie which are used in render request to Grafana.  
- Do you have any additional reverse proxy in front of Grafana/renderer?  
- What does the log of the render service output?
- Can you try running render service using a [custom configuration file](https://github.com/grafana/grafana-image-renderer/blob/master/docs/remote_rendering_using_docker.md#configuration-file) and [enable verbose logging](https://github.com/grafana/grafana-image-renderer/blob/cfb823dc0ee9ba0b93f862ee53eb9427b5242fc0/default.json#L28) by setting it to true?

**Comment by joemillerr** [comment]
Both Grafana and the renderer are behind the same NGINX ingress, so yes its behind a reverse proxy.  Here are the logs from a test alert firing.  Thank you!

[errorlog.txt](https://github.com/grafana/grafana-image-renderer/files/4340877/errorlog.txt)

**Comment by marefr** [comment]
Thanks. Since Grafana returns 401 I see two possibilities. Have you modified how the cookie domain is set in your nginx ingress since renderer sets renderKey cookie domain to `grafana.mydomain.com`? That would explain when you say it works when you set domain to `mydomain.com`.

**Comment by joemillerr** [comment]
Yea you are right, my cookie domain is set to `grafana.mydomain.com`

I'm attempting to modify this using the NGINX ConfigMap spec for proxy-cookie-domain but nothing seems to be working so far.

Would it be possible to pass domain in as a configuration value optionally?  This seems like it will be an extremely finicky parameter that will cause others issues too.

**Comment by marefr** [comment]
@joemillerr but then `grafana.mydomain.com` as cookie path should work/be correct given you access your Grafana instance using `https://grafana.mydomain.com`.

**Comment by joemillerr** [comment]
Yea exactly, so I'm not really sure what is going on here.  I tried a ton of things yesterday on the ingress but nothing made a difference.

**Comment by marefr** [comment]
@joemillerr do you have multiple Grafana instances?

**Comment by joemillerr** [comment]
Yes, currently I have 3 Grafana instances running in this pod using an external backend.

**Comment by marefr** [comment]
@joemillerr make sure to use Grafana v6.7.x to be able to use the public facing URL as rendering callback URL. Since v6.7.x render keys are stored in remote cache (configured database per default).

**Comment by joemillerr** [comment]
@marefr I tried upgrading to 6.7.x and received these logs:

```
{"url":"http://grafana/d-solo/wP1oU4lZk/alert-test?orgId=1&panelId=2&render=1","level":"debug","message":"Render request received"}
{"url":"http://grafana/d-solo/wP1oU4lZk/alert-test?orgId=1&panelId=2&render=1","level":"debug","message":"Render request received"}
{"file":"/tmp/4c9505dc.png","level":"debug","message":"Deleting temporary file"}
{"url":"http://grafana/d-solo/wP1oU4lZk/alert-test?orgId=1&panelId=2&render=1","level":"debug","message":"Connection closed"}
{"message":"10.42.7.76 - - [31/Mar/2020:20:10:19 +0000] \"GET /render?domain=grafana&encoding=&height=500&renderKey=78u5Pfy3phU0vOKCUSlesXQNiWZkFzA0&timeout=30&timezone=&url=http%3A%2F%2Fgrafana%2Fd-solo%2FwP1oU4lZk%2Falert-test%3ForgId%3D1%26panelId%3D2%26render%3D1&width=1000 HTTP/1.1\" 200 33987 \"-\" \"Grafana/6.7.1\"\n","level":"debug"}
{"file":"/tmp/64749af0.png","level":"debug","message":"Deleting temporary file"}
{"url":"http://grafana/d-solo/wP1oU4lZk/alert-test?orgId=1&panelId=2&render=1","level":"debug","message":"Connection closed"}
{"message":"10.42.8.141 - - [31/Mar/2020:20:10:19 +0000] \"GET /render?domain=grafana&encoding=&height=500&renderKey=wVlxtbrFLzt7I1XTANMQ2m4ejqR1fOIy&timeout=30&timezone=&url=http%3A%2F%2Fgrafana%2Fd-solo%2FwP1oU4lZk%2Falert-test%3ForgId%3D1%26panelId%3D2%26render%3D1&width=1000 HTTP/1.1\" 200 33974 \"-\" \"Grafana/6.7.1\"\n","level":"debug"}
```

I actually switched to internal Kubernetes DNS to test that but still had issues.  I can try external again if you'd like but it still looks like theres some problem here.

**Comment by marefr** [comment]
@joemillerr looks good to me. I can't see any issues in those logs

**Comment by joemillerr** [comment]
yea I didn't either but I'm still not seeing renders come through Slack.  Since you've confirmed the logs look good I'll attack from that angle now. I appreciate the help @marefr  It does appear upgrading to 
Grafana 6.7 corrected whatever was happening before.

**Comment by marefr** [comment]
Please try manual render first. Dashboard -> Panel menu -> Share -> Direct link rendered image. Does that work? If so, you have a configuration error with slack.

**Comment by joemillerr** [comment]
Yup it works! Thank you for all your help! I'll take it from here with my Slack admin.
