### ISSUE TITLE
Generated images are not being deleted from /tmp folder

### ISSUE THREAD

**Issue by kerneljack** [grafana/grafana-image-renderer#115]
We are using the grafana-image-render in a separate docker container from Grafana and we've noticed that the `/tmp` folder is full of hundreds of thousands of `png` images like:

```
138f788c.png  
2760f9cb.png
3af9ae80.png
and so on
```

These are not being cleaned up and go back all the way to February when this container was created. Does the image renderer not clean these up at all or am I missing a config option somewhere?

**Comment by marefr** [comment]
Seems they're not being automatically deleted. Thanks for reporting this

**Comment by kerneljack** [comment]
Thanks, is anyone working on this? It's currently filling up our disk every few days. I can write a cronjob to manually delete files but a better solution would be ideal.

**Comment by marefr** [comment]
@kerneljack planning to work on it next week and hopefully release a new version. Sounds like you're generating a lot of images or you have a really small disk? :smiley:

**Comment by kerneljack** [comment]
Thank you, we are definitely generating a ton of images for sure for many alerts, which is expected. The disk is 60GB I believe and I don't really want to make it bigger, I don't think there's any need. The `tmp` folder is full of 22G of `png` files at the moment, which is a lot obviously and taking up a good chunk of the disk. If they were being deleted automatically, then our current disk size is more than sufficient.

**Comment by marefr** [comment]
v1.0.12 will be available soon which includes the fix. Please note that it only does a delete o temporary file after image being rendered and served to the client  Your existing temporary files you have to cleanup manually.
