### ISSUE TITLE
 spawned many zombie processes

### ISSUE THREAD

**Issue by xtlincong** [grafana/grafana-image-renderer#116]
![企业微信截图_6d6ce0fd-487d-476f-9405-d319b6baeb7e](https://user-images.githubusercontent.com/31087368/76960166-dbdc3580-6955-11ea-9b8c-62d32e2c6819.png)

I think this is a bug.
plugin version:1.0.7

**Comment by marefr** [comment]
Please update description using the bug report template https://github.com/grafana/grafana-image-renderer/issues/new?labels=type%3A+bug&template=1-bug_report.md

**Comment by marefr** [comment]
Closing this due to lack of response. We'll consider reopen the issue if you provide more information.
