### ISSUE TITLE
Protocol error, target closed

### ISSUE THREAD

**Issue by ladeak** [grafana/grafana-image-renderer#117]
**What happened**:
Downladed Grafana image renderer zip, extracted plugin-linux-x64-glibc into the plugin folder
Configured environment variables: Ignore https errors, TZ, GRPC port = 50059, logs: rendering:debug

Started Grafana, logs says:
_"Renderer plugin started" logger=rendering grpcPort=50059.000 chromeBin=[...] grpcHost=127.0.0.1_

Then I click for a render.

_"Render request received"...
"Render request failed" logger=rendering error="Error: Protocol error (Target.setDiscoverTargets): Target closed._

- Grafana Image Renderer version: 1.0.10
- Grafana version: 6.5.2
- Installed plugin or remote renderer service: pluring-linux-x64-glibc
- OS Grafana Image Renderer is installed on: Linux
- User OS & Browser: Chrome

**Comment by marefr** [comment]
Haven't seen this error before. 

Would need more detailed information:
- Include exactly how you have configured mentioned environment variables
- What Linux distro and version are you using and what architecture?
- How to you run Grafana (docker, rpm, deb or other) and what is your `[server]` and `[rendering]` configuration?
- Any reverse proxy in front of Grafana, like nginx?

**Comment by ladeak** [comment]
TZ: Europe/Stockholm
ignore https error: true
GRPC port = 50059

Using RHEL 7, running Grafana natively (no docker), it has a reverse proxy in-front of it (apache), doing authentication (Auth_Proxy setup on Grafana)

**Comment by marefr** [comment]
> TZ: Europe/Stockholm
> ignore https error: true
> GRPC port = 50059

You're mixing capital and lowercase letters. This is not helpful trying to understand your setup. You can see at https://github.com/grafana/grafana-image-renderer/blob/master/README.md#environment-variables what information/format I'm expecting 

What is your [server] and [rendering] configuration in Grafana?

**Comment by ladeak** [comment]
I am sorry, but I cannot copy exact preferences.

I do not have any specific server or rendering configuration, that is not on the suggested readme.

GF_RENDERER_PLUGIN_TZ=Europe/Stockholm
GF_RENDERER_PLUGIN_IGNORE_HTTPS_ERRORS=true
GF_RENDERER_PLUGIN_GRPC_PORT=50059

**Comment by marefr** [comment]
Talking about Grafana configuration:
- [[server]](https://grafana.com/docs/grafana/latest/installation/configuration/#server)
- [[rendering]](https://grafana.com/docs/grafana/latest/installation/configuration/#rendering)

Have you read [troubleshoot guide](https://grafana.com/docs/grafana/latest/administration/image_rendering/#troubleshoot-image-rendering)? Please enable debug log, restart Grafana, render an image and capture the Grafana log output and include it here. 

Please replace any sensitive information

**Comment by marefr** [comment]
@ladeak are you by any chance running on cloud foundry or any cloud provider, if so which one?

**Comment by ladeak** [comment]
It is a private 'cloud' solution: https://github.com/Morgan-Stanley/treadmill

**Comment by marefr** [comment]
@ladeak cannot help you further then. Would recommend verifying that you have [IPv6 enabled](https://github.com/grafana/grafana-image-renderer#known-issue-having-ipv6-disabled). Would suggest trying simpler setup first like without HTTPS. If you have possibility to run remote rendering using docker would recommend that.

**Comment by ladeak** [comment]
ack, thank you. It is without https, http only. I will make sure on IPv6, and lastly try remote rendering when possible. Thank you for the suggestion.
