### ISSUE TITLE
Images render but don't load in emails

### ISSUE THREAD

**Issue by lygris** [grafana/grafana-image-renderer#12]
running the docker, i finally got my grafana docker and the renderer docker to talk and the logs don't show any errors. However emails come through looking like this.
![image](https://user-images.githubusercontent.com/22260038/53885220-cf06d100-3fe2-11e9-8de3-4a3a62b924a3.png)

using grafana 6.0 and external image storage is not set.

**Comment by torkelo** [comment]
Please try latest Grafana and enable debug logging

**Comment by marefr** [comment]
Closing this due to seems like misconfiguration of Grafana and lack of response. We'll consider reopen the issue if you provide more information.
