### ISSUE TITLE
How to install in container based Grafana install?

### ISSUE THREAD

**Issue by shanekorbel** [grafana/grafana-image-renderer#13]
I am running the latest Grafana container build which means I don't have a way to do:

git clone into Grafana external plugins folder.
yarn install --pure-lockfile
yarn run build
restart grafana-server , it should log output that the renderer plugin was found and started.

Is there no way to just install this from the plugins browser for Grafana?

**Comment by mbudano** [comment]
Hi, the way I made it work was to take the dockerfile for grafana (https://github.com/grafana/grafana-docker) and modify it to install nodejs 8.x, yarn and copy the files for this plugin, was not easy but it worked.
Best Regards.

**Comment by jonk-nike** [comment]
@mbudano Would you happen to have your dockerfile available as an example?

**Comment by marefr** [comment]
Closing this in favor of #43
