### ISSUE TITLE
Render configuration maxHeight doesn't work on docker config.js

### ISSUE THREAD

**Issue by fruch** [grafana/grafana-image-renderer#132]
**What happened**:
I'm trying to use the docker remote renders to render a dashboard higher then 3000px
But anything I use bigger the height=3000 on the url, I get it trim back to 3000

**What you expected to happen**:
I expect it to render any dashboard as big as I define in maxHeight and maxWidth

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana Image Renderer version: https://hub.docker.com/layers/grafana/grafana-image-renderer/latest/images/sha256-e2e3aede3ef31e37289983eb22cc8c8049f4d76e8f5901180759312140e926a7

- Grafana version:
- Installed plugin or remote renderer service: remote renderer
- OS Grafana Image Renderer is installed on: docker
- User OS & Browser: ubuntu - chrome broswer
- Others:

**Comment by fruch** [comment]
I see that this code i'm trying to use was merge yesterday in #128

and the code isn't there in the latest docker that was built yesterday.

can someone build a updated docker ?

**Comment by marefr** [comment]
We've released a beta of v2.0.0, but you may require Grafana v7 (to be released) to use certain features. See [release](https://github.com/grafana/grafana-image-renderer/releases/tag/v2.0.0-beta1). For docker image there's a 2.0.0-beta1 tag available.

Docs (#130) is something we'll update before stable release.
