### ISSUE TITLE
Trouble with armv7l (docker on Raspberry Pi 3B+)

### ISSUE THREAD

**Issue by jonathandreyer** [grafana/grafana-image-renderer#14]
Hello,
I have run on a docker container (target x86_64) and it is Ok. On target armv7l (Raspberry Pi (3B+), it is not work.

It is crash on line:
https://github.com/grafana/grafana-image-renderer/blob/3989c1dacd2121ca2a1b3e306bef095a0300db62/Dockerfile#L13

**Comment by jonathandreyer** [comment]
After some tests, there is no more crash when dumb-init is removed.

**Comment by marefr** [comment]
Duplicate of #7
