### ISSUE TITLE
Bug: grafana 7 can't download the plugin

### ISSUE THREAD

**Issue by lexfrei** [grafana/grafana-image-renderer#142]
**What happened**:
Grafana 7.0.0-beta3 hangs on downloading this plugin

**What you expected to happen**:
The plugin has to be installed

**How to reproduce it (as minimally and precisely as possible)**:
Deploy grafana:7.0.0-beta3 with `GF_INSTALL_PLUGINS=grafana-image-renderer`

**Anything else we need to know?**:
Nothing appears in plugins directory, nothing in grafana logs

**Environment**:
- Grafana Image Renderer version: 2
- Grafana version: 7.0.0-beta
- Installed plugin or remote renderer service: local plugin
- OS Grafana Image Renderer is installed on: CentOS Linux release 8.1.1911 (Core) on x86_64
- User OS & Browser: N/A
- Others: N/A

**Comment by marefr** [comment]
The plugin is quite big and depending on your network connection it can take a while. Looks like you're using Docker and then you have to read and understand this: https://grafana.com/docs/grafana/latest/administration/image_rendering/#run-in-custom-grafana-docker-image
