### ISSUE TITLE
Missing libraries

### ISSUE THREAD

**Issue by facuxt** [grafana/grafana-image-renderer#145]
**What happened**:
Upgraded to grafana7, and installed new grafana-image-renderer 2, then the notifications images where missing. 

**What you expected to happen**:
Reading the logs, i found this error.
Failed to launch chrome!\n/var/lib/grafana/plugins/grafana-image-renderer/chrome-linux/chrome: error while loading shared libraries: libXcursor.so.1: cannot open shared object file: No such file or directory\n\n\nTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md\n"

Then reading the troubleshooting guide, i find that i may have missing libraries, i installed this.
`sudo apt-get install ca-certificates fonts-liberation gconf-service libappindicator1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils`

Then it works perfectly!

**How to reproduce it (as minimally and precisely as possible)**:
Upgrade from gafana 6.x in Ubuntu and voalá.

**Environment**:
- Grafana Image Renderer version: 2.0
- Grafana version: 7.0
- Installed plugin or remote renderer service: plugin
- OS Grafana Image Renderer is installed on: local
- User OS & Browser: Ubuntu 18.04.03 LTS
- Others:

**Comment by marefr** [comment]
So all is good? It's documented here https://grafana.com/docs/grafana/latest/administration/image_rendering/#grafana-image-renderer-plugin-and-remote-rendering-service

**Comment by facuxt** [comment]
whoops, sorry i didnt saw that, i think it should be worth noting tat link in the plugin page in grafana labs https://grafana.com/grafana/plugins/grafana-image-renderer

**Comment by sachinrase** [comment]
same here 

this on centos 7.2 

```
t=2020-05-19T17:30:30-0700 lvl=eror msg="Render request failed" logger=plugins.backend pluginId=grafana-image-renderer url="https://localhost:5000/d-solo/000000027/admin-influxdb-cluster-health-dashboard?orgId=1&panelId=2&render=1"
 error="Error: Failed to launch chrome!\n/var/lib/grafana/plugins/grafana-image-renderer/chrome-linux/chrome: /lib64/libnss3.so: version `NSS_3.22' not found
 (required by /var/lib/grafana/plugins/grafana-image-renderer/chrome-linux/chrome)\n\n\nTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md\n"
t=2020-05-19T17:30:30-0700 lvl=eror msg="Failed to render and upload alert panel image." logger=alerting.notifier ruleId=36 error="Rendering failed: Error: Failed to launch chrome!\n/var/lib/grafana/plugins/grafana-image-renderer/chrome-linux/chrome: /lib64/libnss3.so: version `NSS_3.22' not found
 (required by /var/lib/grafana/plugins/grafana-image-renderer/chrome-linux/chrome)\n\n\nTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md\n"
```

**Comment by marefr** [comment]
@facuxt There's already a section with link to troubleshooting at the bottom :)

**Comment by marefr** [comment]
@sachinrase if you cannot upgrade your system or dependencies would suggest trying older versions of the plugin and/or https://grafana.com/docs/grafana/latest/administration/image_rendering/#custom-chrome-chromium

**Comment by facuxt** [comment]
Thanks @marefr
