### ISSUE TITLE
Failed to start renderer plugin: Unrecognized remote plugin message (version 2.0.0)

### ISSUE THREAD

**Issue by dgdevops** [grafana/grafana-image-renderer#148]
Hello Team,

I am trying to upgrade Grafana version from 6.7.1 to 7.0.1 on my k8s cluster.
The Grafana is installed via HELM chart and the grafana-image-renderer plugin is installed as a part of the chart. When the Grafana is deployed with version 6.7.1 the pods with the containers come up perfectly and no issues are observed, however when I change the image.tag in the chart to 7.0.1 in the hope to upgrade the instance to 7.0.1 the pods get redeployed but they end up in CrashLoopBackOff state in around 20 seconds. Based on the container logs Grafana starts installing plugins and I could see a log entry "✔ Installed grafana-image-renderer successfully", however the container stops with "grafana stream closed" message. Before that log message I can see the following:

msg="Some plugins failed to load" logger=plugins errors="[Failed to register plugin:\n github.com/grafana/grafana/pkg/util/errutil.Wrap\n /root/msg="Stopped RenderingService" logger=server reason="Failed to start renderer plugin: Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply
msg="plugin failed to exit gracefully" logger=plugins.backend pluginId=grafana-image-renderer
msg="Stopped Stream Manager"
msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl= socket=
msg="A service failed" logger=server err="Failed to start renderer plugin: Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to b
msg="Server shutdown" logger=server reason="Failed to start renderer plugin: Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to ││ grafana stream closed

I also tried using Grafana 7.0.0 docker image, however I could not see any improvement.
I stumbled upon the following issue on GitHub (#21874), however I think my issues is not related to IPv6 as with version 6.7.1 the image renderer start perfectly with address=[::]:3000

**What happened**:
Tried to upgrade Grafana to 7.0.1 from 6.7.1

**What you expected to happen:**
Expected to see the grafana-image-renderer plugin come up

**How to reproduce it (as minimally and precisely as possible)**:
Install Grafana using HELM chart to a k8s cluster (with grafana-image-renderer plugin)
Make sure to use image 7.0.0 or 7.0.1
Connect Grafana to a MySQL database

**Anything else we need to know?:**
-

**Environment:**
Grafana version: 7.0.0 & 7.0.1
Data source type & version: -
OS Grafana is installed on: Kubernetes
User OS & Browser: Windows & Chrome
Grafana plugins: grafana-image-renderer (2.0.0)

**Comment by aknuds1** [comment]
Can you also try installing Grafana to Kubernetes without Helm? It could potentially be a problem with the Helm chart.

**Comment by dgdevops** [comment]
Hello @aknuds1 ,
Thank you for your quick response.
I will definitely try that and get back to you.

**Comment by marefr** [comment]
Since you're running Grafana in a container our recommendation is to run the remote rendering service as a separate container, otherwise you'll have to build a custom Grafana docker image to be able to install the image renderer plugin in it. Please read https://grafana.com/blog/2020/05/07/grafana-7.0-preview-new-image-renderer-plugin-to-replace-phantomjs/ and https://github.com/grafana/grafana-image-renderer/blob/master/docs/remote_rendering_using_docker.md.

Let me know if I misunderstood something.

**Comment by dgdevops** [comment]
Thank you for the assistance @marefr

**Comment by mieseprem** [comment]
Thanks for providing the links.
I personally found this one very helpfull: [custom-image-with-grafana-image-renderer-plugin-pre-installed](https://grafana.com/docs/grafana/latest/installation/docker/#custom-image-with-grafana-image-renderer-plugin-pre-installed)

**Comment by bibincatchme** [comment]
Hello, 
I'm facing the issue with the Grafana image render plugin on the Alert notification setting.(Include image)
I've deployed the Prometheus + Grafana using  https://github.com/helm/charts/tree/master/stable/prometheus-operator

Let me know how I can use Grafana image render plugin (Recently it changed to the separate image)

If any have documentation to do  ?
