### ISSUE TITLE
Upgrade Grafana 6.x to 7.x Image rendering issue 'Failed to get browser version'

### ISSUE THREAD

**Issue by sbarrier** [grafana/grafana-image-renderer#149]
**What happened**:
After upgrading from Grafana 6.x to 7.x local image rendering is not working anymore.

Plugin installed with:
`grafana-cli plugins install grafana-image-renderer`

ldd of _/var/lib/grafana/plugins/grafana-image-renderer/chrome-linux/chrome_ all libraries are present

- added in grafana.ini
[log]
filters = rendering:debug
[plugin.grafana-image-renderer]
rendering_ignore_https_errors = true

if i understood [rendering] section is only for remote rendering server.

- added in /etc/sysconfig/grafana-server
GF_RENDERER_PLUGIN_IGNORE_HTTPS_ERRORS=true

```
lvl=eror msg="Failed to get browser version" logger=plugins.backend pluginId=grafana-image-renderer err="map[error:map[code:ECONNRESET] message:socket hang up target:map[_binaryType:nodebuffer _closeCode:1006 _closeFrameReceived:false _closeFrameSent:false _closeMessage: _closeTimer:<nil> _events:map[] _eventsCount:2 _extensions:map[] _isServer:false _receiver:<nil> _redirects:0 _req:<nil> _sender:<nil> _socket:<nil> protocol: readyState:3 url:ws://127.0.0.1:34664/devtools/browser/accc26fb-2017-48cd-b997-83aea4c75c95] type:error]"

lvl=info msg=Rendering logger=rendering renderer=plugin path="d-solo/iuwfIPkmk/cdh-hdp?orgId=1&panelId=8"

lvl=dbug msg="Calling renderer plugin" logger=rendering renderer=plugin req="url:\"https://localhost:4443/d-solo/iuwfIPkmk/cdh-hdp?orgId=1&panelId=8&render=1\" width:1000 height:500 deviceScaleFactor:1 filePath:\"/var/lib/grafana/png/2gvSX1E6tdCur8ZSsT7H.png\" renderKey:\"ARLhk62oYEae4Yon4XzUISJ4oUyBDDS0\" domain:\"localhost\" timeout:15 "

lvl=eror msg="Render request failed" logger=plugins.backend pluginId=grafana-image-renderer url="https://localhost:4443/d-solo/iuwfIPkmk/cdh-hdp?orgId=1&panelId=8&render=1" error="Error: Protocol error (Target.setDiscoverTargets): Target closed."

vl=eror msg="Failed to render and upload alert panel image." logger=alerting.notifier ruleId=34 error="Rendering failed: Error: Protocol error (Target.setDiscoverTargets): Target closed."
```

**Environment**:
- Grafana Image Renderer version: 2.0.0
- Grafana version: 7.0.1
- Installed plugin or remote renderer service: installed plugin no container
- OS Grafana Image Renderer is installed on: Centos 7.x

**Comment by sbarrier** [comment]
I finally figured the issue after spending few hours of debugging.

`FATAL:platform_font_skia.cc(97)] Check failed: InitDefaultFont()`

For Centos users even if your ldd chrome binary show all libraries don't forget to install fonts and cups!

`yum install cups liberation-serif-fonts liberation-mono-fonts liberation-narrow-fonts liberation-fonts-common`

I hope that will save some time to others users.

**Comment by aknuds1** [comment]
I guess we can close the issue then, thanks for figuring it out :)

**Comment by ArmedChef** [comment]
THANK YOU!

After debugging forever this helped tremendously.  On Ubuntu I needed the _cups_ and _fonts-liberation_ packages.

**Comment by osos** [comment]
... what should I do when using the docker images for both grafana and grafana-image-renderer ?

**Comment by fireheadman** [comment]
I am on ubuntu 20

did the `sudo yum install cups fonts-liberation`
restarted grafana

still seeing:
t=2020-12-01T22:29:58+0000 lvl=eror msg="Failed to get browser version" logger=plugins.backend pluginId=grafana-image-renderer err=map[]

**Comment by Brimstedt** [comment]
Installing chromium might bring you all the dependencies you need
