### ISSUE TITLE
rendering legend

### ISSUE THREAD

**Issue by tonytee** [grafana/grafana-image-renderer#15]
hi guys, sorry if this is not an issue... but i cant find a way to render a graph including the legend-as-table to the right... is this an issue or didnt i rtfm well.. i "only" get the graph itself

thanks and thanks for the work on this priceless plugin

**Comment by marefr** [comment]
@tonytee is this still a problem using the latest version of the plugin and/or Grafana? Otherwise, please provide more information about Grafana version and plugin version. Thanks

**Comment by marefr** [comment]
Closing this due to lack of response. We'll consider reopen the issue if you provide more information.
