### ISSUE TITLE
CALLBACK_URL is ignored which leads to localhost 401 error

### ISSUE THREAD

**Issue by formtapez** [grafana/grafana-image-renderer#151]
**What happened**:
My Grafana installation is working fine, but installed standalone plugin of grafana-image-renderer is not able to produce renderings for my warning-emails.
It doesnt respect the (multiple set) callback_url and tries to access localhost instead.
localhost would technically work (that is why i let ignore the https certificate errors), but it gets a 401 error instead.
When i try the localhost rendering url from the logfile in my browser, it shows the dashboards just fine.

/var/log/grafana/grafana.log:
> t=2020-06-04T09:23:01+0200 lvl=info msg="New state change" logger=alerting.resultHandler ruleId=1 newState=ok prev state=alerting
> t=2020-06-04T09:23:01+0200 lvl=info msg=Rendering logger=rendering renderer=plugin path="d-solo/VSXXxXxmz/dashboardname?orgId=1&panelId=6"
> t=2020-06-04T09:23:01+0200 lvl=dbug msg="Calling renderer plugin" logger=rendering renderer=plugin req="url:\"https://localhost:3000/d-solo/VSXXxXxmz/dashboardname?orgId=1&panelId=6&render=1\" width:1000 height:500 deviceScaleFactor:1 filePath:\"/var/lib/grafana/png/kFcsf3fsdfxWoJK2mEfn.png\" renderKey:\"5ROvQP3mYg7ZdfDFdfMv7IYqieD6OHLV\" domain:\"localhost\" timeout:15 "
> t=2020-06-04T09:23:16+0200 lvl=info msg="Rendering timed out" logger=rendering renderer=plugin
> t=2020-06-04T09:23:16+0200 lvl=eror msg="Failed to render and upload alert panel image." logger=alerting.notifier ruleId=1 error="Timeout error. You can set timeout in seconds with &timeout url parameter"
> t=2020-06-04T09:23:16+0200 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses=[my@email.com] singleEmail=false
> t=2020-06-04T09:23:17+0200 lvl=eror msg="Failed to get render key from cache" logger=rendering renderer=plugin error="cache item not found"
> t=2020-06-04T09:23:17+0200 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/d-solo/VSXXxXxmz/dashboardname status=401 remote_addr=[::1] time_ms=1 size=32 referer=
> t=2020-06-04T09:23:17+0200 lvl=eror msg="Browser console error" logger=plugins.backend pluginId=grafana-image-renderer msg="Failed to load resource: the server responded with a status of 401 (Unauthorized)" url="https://localhost:3000/d-solo/VSXXxXxmz/dashboardname?orgId=1&panelId=6&render=1"
> t=2020-06-04T09:23:33+0200 lvl=eror msg="Render request failed" logger=plugins.backend pluginId=grafana-image-renderer error="TimeoutError: waiting for function failed: timeout 15000ms exceeded" url="https://localhost:3000/d-solo/VSXXxXxmz/dashboardname?orgId=1&panelId=6&render=1"

**What you expected to happen**:
grafana-image-renderer respects the callback URL, doesnt get a 401 error and renders my image just fine.

**How to reproduce it (as minimally and precisely as possible)**:
Install Ubuntu 18.04.4 LTS, install grafana via apt, and grafana-image-renderer via grafana-cli.
Set some callback_url and see it doesnt get respected.

**Anything else we need to know?**:
/etc/grafana/grafana.ini:
> [server]
> protocol = https
> http_port = 3000
> domain = myhost.mydomain.com
> root_url = https://myhost.mydomain.com:3000
> 
> 
> [rendering]
> callback_url = https://myhost.mydomain.com:3000/
> 
> [plugins.grafana-image-renderer]
> callback_url = https://myhost.mydomain.com:3000/

/etc/default/grafana-server:
> GF_RENDERER_PLUGIN_IGNORE_HTTPS_ERRORS=true
> GF_RENDERING_CALLBACK_URL=https://myhost.mydomain.com:3000/
> GF_RENDERER_PLUGIN_CALLBACK_URL=https://myhost.mydomain.com:3000/
> GF_RENDERER_PLUGIN_LOG_LEVEL=debug
> GF_RENDERER_PLUGIN_RENDERING_VERBOSE_LOGGING=true
> GF_RENDERER_PLUGIN_RENDERING_ARGS=--no-sandbox,--no-proxy-server

PS: I was unable to configure IGNORE_HTTPS_ERRORS via grafana.ini. The only way that worked was via environment variables in /etc/default/grafana-server. So it seems to be there is more broken...

**Environment**:
- Grafana Image Renderer version: 2.0.0
- Grafana version: 7.0.1
- Installed plugin or remote renderer service: plugin installed via grafana-cli
- OS Grafana Image Renderer is installed on: Ubuntu 18.04.4 LTS
- User OS & Browser: Ubuntu 18.04.4 LTS

**Comment by formtapez** [comment]
Thanks for the hint to defaults.ini - That file is better than the documentation :-)
With that correct section and parameter-names i cleared my environment-vars and shorted my grafana.ini modifications as follows:
(no [rendering] section anymore)

> [server]
> protocol = https
> http_port = 3000
> domain = myhost.mydomain.com
> root_url = https://myhost.mydomain.com:3000
> 
> [plugin.grafana-image-renderer]
> rendering_ignore_https_errors = true
> rendering_verbose_logging = true
> rendering_args = --no-sandbox,--no-proxy-server

Unfortunately, i still get that error 401 (Unauthorized).
Or has it something to do with that "Failed to get render key from cache" from 2 lines above that 401?

> Rendering logger=rendering renderer=plugin path="d-solo/VSXXxXxmz/dashboardname?orgId=1&panelId=6"
> Calling renderer plugin" logger=rendering renderer=plugin req="url:\"https://localhost:3000/d-solo/VSXXxXxmz/dashboardname?orgId=1&panelId=6&render=1\" width:1000 height:500 deviceScaleFactor:1 filePath:\"/var/lib/grafana/png/MlDIWaafucOUTRzquFFZ.png\" renderKey:\"aIPL55n6dVEqaBs1sxThZ6a4ZKE2qVcL\" domain:\"localhost\" timeout:15 "
> Rendering timed out" logger=rendering renderer=plugin
> Failed to render and upload alert panel image." logger=alerting.notifier ruleId=1 error="Timeout error. You can set timeout in seconds with &timeout url parameter"
> Sending alert notification to" logger=alerting.notifier.email addresses=[my@email.com] singleEmail=false
> Failed to get render key from cache" logger=rendering renderer=plugin error="cache item not found"
> Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/d-solo/VSXXxXxmz/dashboardname status=401 remote_addr=[::1] time_ms=0 size=32 referer=
> Browser console error" logger=plugins.backend pluginId=grafana-image-renderer msg="Failed to load resource: the server responded with a status of 401 (Unauthorized)" url="https://localhost:3000/d-solo/VSXXxXxmz/dashboardname?orgId=1&panelId=6&render=1"
> Render request failed" logger=plugins.backend pluginId=grafana-image-renderer error="TimeoutError: waiting for function failed: timeout 15000ms exceeded" url="https://localhost:3000/d-solo/VSXXxXxmz/dashboardname?orgId=1&panelId=6&render=1"

**Comment by marefr** [comment]
Can you please try and change to:
```
[server]
protocol = https
http_port = 3000
domain = localhost
root_url = https://myhost.mydomain.com:3000
```

**Comment by formtapez** [comment]
I tried that again and get the exact same error as above :-(

**Comment by bibarrav** [comment]
Hi, I have the same issue with the Remote Renderer, always gets 401 when try to access Grafana CALLBACK_URL.  I'm wondering how suppose the rendered can authenticate to Grafana?

Here my logs in Renderer:
{"level":"info","message":"HTTP Server started, listening at http://localhost:8081"}
{"msg":"Failed to load resource: the server responded with a status of 401 (Unauthorized)","url":"http://grafana-grafana/api/dashboards/uid/000000012","level":"error","message":"Browser console error"}
{"msg":"Failed to load resource: the server responded with a status of 401 (Unauthorized)","url":"http://grafana-grafana/api/login/ping","level":"error","message":"Browser console error"}
{"msg":"Failed to load resource: the server responded with a status of 401 (Unauthorized)","url":"http://grafana-grafana/logout","level":"error","message":"Browser console error"}
{"url":"/render?deviceScaleFactor=1.000000&domain=grafana-grafana&encoding=&height=500&renderKey=Ih1djX21WRNLmsLQphpalY8j7XBEd0Gt&timeout=15&timezone=&url=http%3A%2F%2Fgrafana-grafana%3A80%2Fd-solo%2F000000012%2Fkubernetes-nodes-status-on-global-5%3ForgId%3D1%26panelId%3D5%26render%3D1&width=1000","stack":"TimeoutError: waiting for function failed: timeout 15000ms exceeded\n    at new WaitTask (/usr/src/app/node_modules/puppeteer/lib/DOMWorld.js:549:28)\n    at DOMWorld.waitForFunction (/usr/src/app/node_modules/puppeteer/lib/DOMWorld.js:454:12)\n    at Frame.waitForFunction (/usr/src/app/node_modules/puppeteer/lib/FrameManager.js:657:28)\n    at Page.waitForFunction (/usr/src/app/node_modules/puppeteer/lib/Page.js:1144:29)\n    at Browser.<anonymous> (/usr/src/app/build/browser/browser.js:174:24)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/build/browser/browser.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","level":"error","message":"Request failed"}
{"msg":"Failed to load resource: the server responded with a status of 401 (Unauthorized)","url":"http://grafana-grafana/api/alerts/states-for-dashboard?dashboardId=15","level":"error","message":"Browser console error"}
{"msg":"Failed to load resource: the server responded with a status of 401 (Unauthorized)","url":"http://grafana-grafana/api/annotations?from=1599004800000&to=1599065236702&dashboardId=15","level":"error","message":"Browser console error"}
{"msg":"Failed to load resource: the server responded with a status of 401 (Unauthorized)","url":"http://grafana-grafana/api/datasources/proxy/1/api/v1/query_range?query=100*(node_memory_MemTotal_bytes%7Bprometheus_group%3D%22global-5%22%7D%20-%20node_memory_MemFree_bytes%7Bprometheus_group%3D%22global-5%22%7D%20-%20node_memory_Buffers_bytes%7Bprometheus_group%3D%22global-5%22%7D%20-%20node_memory_Cached_bytes%7Bprometheus_group%3D%22global-5%22%7D)%20%2F%20node_memory_MemTotal_bytes%7Bprometheus_group%3D%22global-5%22%7D%20&start=1599004800&end=1599065160&step=120","level":"error","message":"Browser console error"}

Here my logs in Grafana:
t=2020-09-02T16:46:01+0000 lvl=info msg=Rendering logger=rendering renderer=http path="d-solo/000000012/kubernetes-nodes-status-on-global-5?orgId=1&panelId=5"
t=2020-09-02T16:46:01+0000 lvl=dbug msg="calling remote rendering service" logger=rendering renderer=http url="http://grafana-renderer:8081/render?deviceScaleFactor=1.000000&domain=grafana-grafana&encoding=&height=500&renderKey=Ih1djX21WRNLmsLQphpalY8j7XBEd0Gt&timeout=15&timezone=&url=http%3A%2F%2Fgrafana-grafana%3A80%2Fd-solo%2F000000012%2Fkubernetes-nodes-status-on-global-5%3ForgId%3D1%26panelId%3D5%26render%3D1&width=1000"
t=2020-09-02T16:46:02+0000 lvl=info msg="Request Completed" logger=context userId=3 orgId=1 uname=bibarrav@Falabella.cl method=GET path=/api/datasources/proxy/1/api/v1/metadata status=404 remote_addr=190.153.149.210 time_ms=22 size=19 referer="https://monitor-beta.buffetcloud.io/d/000000012/kubernetes-nodes-status-on-global-5?editPanel=5&orgId=1"
t=2020-09-02T16:46:16+0000 lvl=eror msg="Failed to send request to remote rendering service." logger=rendering renderer=http error="Get \"http://grafana-renderer:8081/render?deviceScaleFactor=1.000000&domain=grafana-grafana&encoding=&height=500&renderKey=Ih1djX21WRNLmsLQphpalY8j7XBEd0Gt&timeout=15&timezone=&url=http%3A%2F%2Fgrafana-grafana%3A80%2Fd-solo%2F000000012%2Fkubernetes-nodes-status-on-global-5%3ForgId%3D1%26panelId%3D5%26render%3D1&width=1000\": context deadline exceeded"
t=2020-09-02T16:46:16+0000 lvl=eror msg="Failed to render and upload alert panel image." logger=alerting.notifier ruleId=1 error="Failed to send request to remote rendering service. Get \"http://grafana-renderer:8081/render?deviceScaleFactor=1.000000&domain=grafana-grafana&encoding=&height=500&renderKey=Ih1djX21WRNLmsLQphpalY8j7XBEd0Gt&timeout=15&timezone=&url=http%3A%2F%2Fgrafana-grafana%3A80%2Fd-solo%2F000000012%2Fkubernetes-nodes-status-on-global-5%3ForgId%3D1%26panelId%3D5%26render%3D1&width=1000\": context deadline exceeded"
t=2020-09-02T16:46:16+0000 lvl=info msg="Executing slack notification" logger=alerting.notifier.slack ruleId=1 notification=buffetcloud-alerts
t=2020-09-02T16:46:18+0000 lvl=eror msg="Failed to get render key from cache" logger=rendering renderer=http error="cache item not found"
t=2020-09-02T16:46:18+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/dashboards/uid/000000012 status=401 remote_addr=X.X.X.X time_ms=0 size=32 referer="http://grafana-grafana/d-solo/000000012/kubernetes-nodes-status-on-global-5?orgId=1&panelId=5&render=1"

**Comment by bibarrav** [comment]
I figure it out that the problem is the time out, because alerts are generated with 15s timeouts (I don't know where this timeout comes from) and it fails, but creating a direct image link works fine (this are created with 60s timeout).  So, I'm reviewing the Image Renderer performance and I see that it needs more CPU resources, and after putting more CPU, the errors dissapear!.

Now, testing alerts to Slack, messages are not comming with images, so checking the code, the slack notification is sent with an image only if they have a Slack Bot Token or Public URL from Grafana.  So, I add a new entry in my config enabling local provider for external_image_storage, and finally I start receiving notifications with graphs (images).

The config in grafana.ini:
...
[external_image_storage]
provider = local
...

:)

**Comment by maudrid** [comment]
> I figure it out that the problem is the time out, because alerts are generated with 15s timeouts (I don't know where this timeout comes from) and it fails, but creating a direct image link works fine (this are created with 60s timeout). So, I'm reviewing the Image Renderer performance and I see that it needs more CPU resources, and after putting more CPU, the errors dissapear!.
> 
> Now, testing alerts to Slack, messages are not comming with images, so checking the code, the slack notification is sent with an image only if they have a Slack Bot Token or Public URL from Grafana. So, I add a new entry in my config enabling local provider for external_image_storage, and finally I start receiving notifications with graphs (images).
> 
> The config in grafana.ini:
> ...
> [external_image_storage]
> provider = local
> ...
> 
> :)

Thanks so much! Assigning more CPU resource fixed it for me

**Comment by AgnesToulet** [comment]
Often, when having performance issues, the 401 error will be returned because the Grafana request will timeout and delete the renderKey before the rendering request reaches the point of navigating to the Grafana page.

A fix to this issue https://github.com/grafana/grafana-image-renderer/issues/186 would fix this misleading error.

**Comment by juyelhushen** [comment]
![rendering](https://user-images.githubusercontent.com/101938468/182819966-50f2a0bd-f99a-444b-9fe3-d5542369fe06.png)
 facing this  problem is anyone know please help
