### ISSUE TITLE
Renderer times out for invalid Grafana panels, should fail

### ISSUE THREAD

**Issue by aknuds1** [grafana/grafana-image-renderer#158]
**What happened**:
When trying to access an invalid Grafana panel, effectively as in #157, the renderer plugin times out instead of bailing with an error.

**What you expected to happen**:
I expected the plugin to bail with an error when trying to render an invalid panel (Grafana reports it as such).

**How to reproduce it (as minimally and precisely as possible)**:
Try to render a Grafana panel that hasn't yet been saved. Access the URL directly and  see that it's an invalid panel.

**Comment by marefr** [comment]
Closing this in favor of https://github.com/grafana/grafana/issues/25648
