### ISSUE TITLE
Rendering not waiting for panel to load

### ISSUE THREAD

**Issue by mbudano** [grafana/grafana-image-renderer#16]
Is there a way to set a time to wait for the panel to load? I'm having problems with several dashboards that are been render before the panels in them are ready (with data).
So I end up with an image of several panels been loaded.

**Comment by hailong1004** [comment]
Have the same problem, set different timeout, but it does not take effect, when the panel needs more than 10s to get the data, those pictures have no data, my grafana version is 6.2.5

**Comment by kjetilmjos** [comment]
Did you find out if there is some solution to the rendering time issue?

**Comment by MarkTurbo** [comment]
I'm hitting exactly the same issue. Getting back PNGs of panels with the spinning 'loading' icon in the corner! Any updates about this issue?

**Comment by kjetilmjos** [comment]
I did not find anything more about it

**Comment by mbudano** [comment]
I was unable to find a solution, I was using the render function to show an image in a nodejs program, but eventually I changed the code to use puppeteer library

**Comment by marefr** [comment]
@MarkTurbo are you rendering a single panel or a full dashboard?

**Comment by MarkTurbo** [comment]
@marefr A full dashboard that consists of 15 SingleStat panels...

![image](https://user-images.githubusercontent.com/29234864/63187372-92201b00-c013-11e9-87f4-c2b459022064.png)

**Comment by marefr** [comment]
Okay, thanks. This is currently not built for supporting rendering full dashboards, but probably something we would like to support in the future.

**Comment by NateZimmer** [comment]
A query parameter for waiting would be useful.. I keep getting blank tables: 
![image](https://user-images.githubusercontent.com/1478536/80246524-2b3b1300-8632-11ea-9a2a-3e8d3598c5a8.png)

**Comment by marefr** [comment]
@NateZimmer is that the buildin table panel or a community plugin?

**Comment by NateZimmer** [comment]
@marefr that is the built in table panel. Using Grafana v6.3.5. I have this occasionally happen on plots as well. 

My temporary hack-a-round is to set an image size threshold and if the downloaded image is below the anticipated size, re-download.

**Comment by alitoufighi** [comment]
Experiencing the same issue when setting a long time range. When I use 2~3 days, it renders fine, but for the range of 7 days it fails and I only get a "No Data". The panels are just normal graphs, reading data from a Prometheus datasource (configured to read metrics in the server-side).

**Comment by alitoufighi** [comment]
It turned out to be a problem with Prometheus step values. Increasing the "Max data points" in the query options fixed it for me. I no longer think this is an issue with the rendering tool, but with how we query for the data.
