### ISSUE TITLE
Text panel rendering broken since Grafana 7.1.0

### ISSUE THREAD

**Issue by thibmac** [grafana/grafana-image-renderer#170]
**What happened**:

I am unable to render text panels since Grafana version 7.1.0
Here is the page we are getting :

![image](https://user-images.githubusercontent.com/17719479/90227109-57161a80-de14-11ea-87b9-c14e88daad24.png)

**What you expected to happen**:

Rendered image of a text panel from the dashboard  i'm querying.

**How to reproduce it (as minimally and precisely as possible)**:

On grafana version > 7.1.0 :

1. Create a text panel on a random dashboard
2. In panel options, "Share panel"
3. Link tab, click "Direct link rendered image"
4. Default timeout is 60 seconds, it should show the error page after 60 seconds.

Tested on 2 different environments, both debian buster with same results, I'll add more detail to the bug reproducing these steps works for you

**Environment**:
- grafana-renderer-version : 2.0.0
- Grafana version: 7.1.x
- Installed plugin or remote renderer service: local plugin
- OS Grafana Image Renderer is installed on: Debian Buster 10.5
- User OS & Browser: Tested on Chrome,Firefox and grafana-reporter

**Comment by lucasbaronio** [comment]
The same happens to me

**Comment by jgodoy2017** [comment]
I must thank WMware for the snapshot functionality. Had to roll back a production environment due to this bug.

**Comment by Didr** [comment]
Supposedly fixed in Grafana 7.2.
https://github.com/grafana/grafana/pull/27083

**Comment by thibmac** [comment]
> Supposedly fixed in Grafana 7.2.
> [grafana/grafana#27083](https://github.com/grafana/grafana/pull/27083)

It is fixed ! closing this issue then, thanks
