### ISSUE TITLE
Setting GF_DATAPROXY_TIMEOUT does not extend timeout  

### ISSUE THREAD

**Issue by chasen-bettinger** [grafana/grafana-image-renderer#173]
**What happened**:
I set GF_DATAPROXY_TIMEOUT variable to 120 expecting that to increase the timeout of rendering panels to 120 seconds. When attempting to view a panel that takes longer than 30 seconds to render, the software times out and throw an error.

**What you expected to happen**:

The docker image uses the environment variable I set when running the docker container (`-e GF_DATAPROXY_TIMEOUT=120`). When viewing a panel, it uses the value I specified in my environment variable as the timeout value instead of the default value. 

**How to reproduce it (as minimally and precisely as possible)**:
```
docker run -d \
    -p 3000:3000 \
    --name=grafana \
    -e GF_DATAPROXY_TIMEOUT=120 \
    grafana-custom:latest
```

- Go into Grafana web portal
- Create a dashboard
- Create a panel that takes > 30 secs to load
- Observe that the panel still timeouts at 30 secs despite you changing the value of the timeout to 120.

**Environment**:
- Grafana Image Renderer version: Latest
- Grafana version: Latest
- Installed plugin or remote renderer service: plugin
- OS Grafana Image Renderer is installed on: Docker image
- User OS & Browser: Mac OS & Chrome

**Comment by marefr** [comment]
You probably want to extend the rendering timeout using the [timeout query string parameter](https://grafana.com/docs/grafana/latest/dashboards/share-panel/#direct-link-rendered-image.)
