### ISSUE TITLE
Rendering fails with authentication protected datasources

### ISSUE THREAD

**Issue by adamcstephens** [grafana/grafana-image-renderer#177]
**What happened**:
Unable to render images due to lack of authentication to datasource.

**What you expected to happen**:
Image renderer to authenticate to datasource to query data for rendering

**How to reproduce it (as minimally and precisely as possible)**:
1. Add authentication to a datasource, e.g. basic authentication in front of Prometheus or Graphite.
2. Add datasource to Grafana, seems to affect both `direct` and `proxy` source types
3. Attempt to render a panel into an image

**Anything else we need to know?**:
The issue was reported in the forum as far back as June, for type `proxy`: https://community.grafana.com/t/grafana-image-renderer-data-source-authentication/32312

As-is, there seems to be no way to provide authentication credentials to the image renderer service, ensuring that any authenticated datasource will fail to render.

**Environment**:
- Grafana Image Renderer version: 2.0.0
- Grafana version: 7.1.0
- Installed plugin or remote renderer service: Both
- OS Grafana Image Renderer is installed on: Ubuntu 16.04.x
- User OS & Browser: Chrome, Firefox, doesn't matter.
- Others:

**Comment by MathieuEtchepare** [comment]
Hi, I have the same issue, is a fix planned for soon?

**Comment by aknuds1** [comment]
Sorry, we haven't started working on this yet. We have a lot of different issues to tend to.
