### ISSUE TITLE
Get 401 for Alert tirggered rendering

### ISSUE THREAD

**Issue by mecseid** [grafana/grafana-image-renderer#178]
**What happened**:
The image renderer got 401 (Unauthorized) when callback the grafana instance.

**What you expected to happen**:
Got the proper message on Slack with the generated image.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy the latest Helm stable version from grafana:
https://github.com/helm/charts/tree/master/stable/grafana

Deploy the grafana image renderer with these deployment files:
https://gist.github.com/mecseid/880baf2275a382741be64e96a31d4bb0

**Anything else we need to know?**:
The direct link rendered image feature works but terrible slow (~20 seconds / image).

**Environment**:
- Grafana Image Renderer version: 2.0.0
- Grafana version: v7.1.1 (3039f9c3bd)
- Installed plugin or remote renderer service: remote
- OS Grafana Image Renderer is installed on: Kubernetes on top of CoreOS
- User OS & Browser: Chrome latest stable

**Comment by marefr** [comment]
Have you tried without resources limits? Do you have enough CPU/Memory resources available for the image rendering service?

**Comment by mecseid** [comment]
Yes and yes. :)
I enabled the metrics endpoint and monitored with Prometheus.
On the Grafana dashboard I didn't see any resource problem (it was only used 50-150mCPU and ~100-200MB memory)

**Comment by aporquez** [comment]
I also encountered the 401. Adding the --no-proxy-server in the RENDERING_ARGS resolved it for me.

This settings is working but the image rendered by the "Direct link rendered image" is the home page and not the panel.
- GF_RENDERING_SERVER_URL:  http://grafana-image-renderer.monitoring.svc.cluster.local/render
- GF_RENDERING_CALLBACK_URL: http://grafana.monitoring.svc.cluster.local

The image rendered by the "Direct link rendered image" is the correct panel if I use this URLs.
- GF_RENDERING_SERVER_URL:  https://domain.com/image-renderer/render
- GF_RENDERING_CALLBACK_URL: https://domain.com/grafana



**Environment:**

**Grafana Image Renderer version: 2.0.0
Grafana version: v7.2.0-ubuntu
Installed plugin or remote renderer service: remote
OS Grafana Image Renderer is installed on: Kubernetes under AKS
User OS & Browser: Chrome latest stable**

**Comment by AgnesToulet** [comment]
As mentioned here: https://github.com/grafana/grafana-image-renderer/issues/151#issuecomment-910462759, this 401 error probably comes from a timeout issue:
> Often, when having performance issues, the 401 error will be returned because the Grafana request will timeout and delete the renderKey before the rendering request reaches the point of navigating to the Grafana page.
> 
> A fix to this issue #186 would fix this misleading error.

You said that rendering the image took ~20 seconds, the timeout for an alert is 15 seconds per default (this [config setting](https://grafana.com/docs/grafana/latest/administration/configuration/#notification_timeout_seconds) divided by 2) so it's why you don't have the image.

A rendering request should not take more than ~2/3 seconds if the data source request is fast. If you have enough resources, the problem may come from the data source request. How long does it take to render the panel in Grafana?
