### ISSUE TITLE
many zombie processes are generated

### ISSUE THREAD

**Issue by YaKazama** [grafana/grafana-image-renderer#179]
**What happened**:

I'm running grafana-server and grafana-image-renderer plugin in Kubernetes, when I click "Direct link rendered image" to generate a picture, after the picture is generated, many zombie processes will be generated.

**What you expected to happen**:

After the picture responds, no zombie process will be generated.

**How to reproduce it (as minimally and precisely as possible)**:

"Panel" -> "Share" -> "Share Panel" -> click "Direct link rendered image", and then execute the command "top -c", 5 will be added to "zombie".

**Anything else we need to know?**:

Use the latest version of chrome browser, there will be the same problem.

**Environment**:
- Grafana Image Renderer version: v2.0.0
- Grafana version: 7.1.1
- Installed plugin or remote renderer service:
- OS Grafana Image Renderer is installed on: CentOS 7、18.05.0-ce、kubernetes 1.16
- User OS & Browser: CentOS 7、18.05.0-ce、kubernetes 1.16
- Others:

the

**Comment by robonuka** [comment]
Yes, it's true!
Moreover, 4 zombies always stay in processes even if this plugin just installed in grafana.
If you kill these 4 zombies manually - this plugin will summon them again.

**Comment by robonuka** [comment]
SOLUTION: you should start the "/run.sh" thru dumb-init utility.
So you need to reassemble grafana docker image with this solution.
Here is my Dockerfile. Just for example.
---
ARG GRAFANA_VERSION="7.2.1"
FROM grafana/grafana:${GRAFANA_VERSION}
ARG GF_INSTALL_IMAGE_RENDERER_PLUGIN="true"
ENV GF_PATHS_PLUGINS="/var/lib/grafana-plugins"

RUN mkdir -p "$GF_PATHS_PLUGINS" && \
    chown -R grafana:grafana "$GF_PATHS_PLUGINS"

RUN if [ $GF_INSTALL_IMAGE_RENDERER_PLUGIN = "true" ]; then \
    echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories && \
    echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories && \
    echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories && \
    apk --no-cache  upgrade && \
    apk add --no-cache dumb-init udev curl openssl nss-tools ttf-opensans chromium && \
    rm -rf /tmp/* && \
    rm -rf /usr/share/grafana/tools/phantomjs; \
fi

USER grafana

ENV GF_RENDERER_PLUGIN_CHROME_BIN="/usr/bin/chromium-browser"

RUN if [ $GF_INSTALL_IMAGE_RENDERER_PLUGIN = "true" ]; then \
    grafana-cli \
        --pluginsDir "$GF_PATHS_PLUGINS" \
        --pluginUrl https://github.com/grafana/grafana-image-renderer/releases/latest/download/plugin-linux-x64-glibc-no-chromium.zip \
        plugins install grafana-image-renderer; \
fi

ARG GF_INSTALL_PLUGINS="\
alexanderzobnin-zabbix-app,\
blackmirror1-statusbygroup-panel,\
briangann-gauge-panel,\
btplc-status-dot-panel,\
agenty-flowcharting-panel,\
grafana-piechart-panel,\
grafana-worldmap-panel,\
michaeldmoore-multistat-panel,\
mtanda-histogram-panel,\
yesoreyeram-boomtable-panel,\
zuburqan-parity-report-panel\
"

RUN if [ ! -z "${GF_INSTALL_PLUGINS}" ]; then \
    OLDIFS=$IFS; \
        IFS=','; \
    for plugin in ${GF_INSTALL_PLUGINS}; do \
        IFS=$OLDIFS; \
        grafana-cli --pluginsDir "$GF_PATHS_PLUGINS" plugins install ${plugin}; \
    done; \
fi

ENTRYPOINT ["dumb-init"]

CMD ["/run.sh"]

**Comment by marefr** [comment]
Thanks. Closing this since it isn't a problem and solution has been provided.
