### ISSUE TITLE
EADDRNOTAVAIL: address not available 

### ISSUE THREAD

**Issue by vijayakumarbathini** [grafana/grafana-image-renderer#193]
**What happened**:

Getting address not available when I try to start image renderer on any port

**What you expected to happen**:

Image renderer starting sucessfully

**How to reproduce it (as minimally and precisely as possible)**:

Compose file

```
version: '3.2'
services:
  dxi-grafana-image-renderer:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
        HTTP_HOST : 10.230.160.69
        HTTP_PORT : 9999
```

**Anything else we need to know?**:

**Environment**:
- Grafana Image Renderer version:
- Grafana version:
- Installed plugin or remote renderer service:
- OS Grafana Image Renderer is installed on:
- User OS & Browser:
- Others:

**Comment by aknuds1** [comment]
Can you paste the error output you get?

**Comment by AgnesToulet** [comment]
I'm closing this issue since it needs more information and hasn't had any activity recently. Please re-open it if you still have the issue and have more information to share (detailed error log).
