### ISSUE TITLE
Rendering failed

### ISSUE THREAD

**Issue by PragueJoker** [grafana/grafana-image-renderer#194]
Rendering failed: Time
outError: Timed out after 30000 ms while trying to connect to Chrome! The only Chrome revision guaranteed to work is r706915

**Environment**:
- Grafana Image Renderer version: 2.0.0
- Grafana version: 7.2.1
- Installed plugin or remote renderer service:plugin
- OS Grafana Image Renderer is installed on: linux 
- User OS & Browser:mac chrome
- Others:

**Comment by AgnesToulet** [comment]
Is this still an issue with the latest version of the plugin? If so, please share more logs about the issue.

To enable debug/verbose logs, you need to update your Grafana .ini file with the following settings:
```
[log]
filters = rendering:debug,plugins.backend:debug

[plugin.grafana-image-renderer]
rendering_verbose_logging = true
rendering_dumpio = true
```

**Comment by AgnesToulet** [comment]
Closing this issue as it may have been fixed in the latest versions. Please open it again with more information if it's still an issue.
