### ISSUE TITLE
Implement support for PDF rendering

### ISSUE THREAD

**Issue by alexanderzobnin** [grafana/grafana-image-renderer#20]
We need to add support for rendering panels and dashboards into PDF. Since image-renderer plugin uses puppeteer, it should be quite simple. I've made some initial research and found few pitfalls:
- We have to set a proper width of the dashboard (in pixels), otherwise, panel legend overlaps graphs.
![Screenshot from 2019-08-01 13-10-10](https://user-images.githubusercontent.com/4932851/62285188-cc0ef000-b45d-11e9-963d-eac0e8ef4c7f.png)
- We have to handle panels lazy loading (I think we can set a height of the browser viewport to the actual page height to show all panels) and make sure all queries are finished. This helps to avoid empty graphs. For this purpose we can use `waitUntil: 'networkidle2'` param:
  ```
  page.goto(options.url, { waitUntil: 'networkidle2' });
  ```
  ![Screenshot from 2019-08-01 13-14-35](https://user-images.githubusercontent.com/4932851/62285476-53f4fa00-b45e-11e9-8795-183ab8e9e6b1.png)

**Comment by marefr** [comment]
We have an open PR #24 suggesting to add `waitUntil: 'networkidle0'` param. Are you suggesting `networkidle2` given that Grafana does pings to the backend from time to time?

**Comment by alexanderzobnin** [comment]
Closing this because we decided to render pdf on grafana-server (this approach has some benefits).
