### ISSUE TITLE
More than just the graph is rendered

### ISSUE THREAD

**Issue by kvz** [grafana/grafana-image-renderer#201]
**What happened**:

When i request a rendered version of the graph, i get a PNG of a whole section of the grafana dashboard

**What you expected to happen**:

To just get a PNG of the graph I requested, without extra graphs and Grafana artwork

**How to reproduce it (as minimally and precisely as possible)**:

We installed the latest versions of Prometheus, Grafana & Grafana Image Renderer. I'm running with default Grafana configuration except for:

```ini
[paths]
data         = /srv/shared/grafana/data
logs         = /srv/shared/log/grafana
plugins      = /srv/shared/grafana/plugins
provisioning = /srv/shared/grafana/conf/provisioning
[server]
http_addr           = 127.0.0.1
http_port           = 3000
root_url            = https://vbox1-local-development.transloadit.com/grafana
serve_from_sub_path = true
[dashboards]
default_home_dashboard_path = /srv/shared/grafana/jsondashboards/regional.json
[auth.anonymous]
org_name = Transloadit
[log]
mode = syslog
[log.syslog]
tag = grafana
[external_image_storage]
provider = s3
[external_image_storage.s3]
bucket     = XXX
region     = us-east-1
path       = /grafana/renderings
access_key = XXX
secret_key = XXX
```

**Anything else we need to know?**:

Here is an actual PNG that was returned instead of just one graph:

![image](https://user-images.githubusercontent.com/26752/104020728-ee15b180-51bd-11eb-85ec-58dba7ccf6a1.png)

I got this picture by clicking here:

![image](https://user-images.githubusercontent.com/26752/104025209-90389800-51c4-11eb-9b39-75a154676225.png)

**Environment**:
- Grafana Image Renderer version: v1.0.0
- Grafana version: Grafana v7.3.6
- Installed plugin or remote renderer service: Remote Renderer Service
- OS Grafana Image Renderer is installed on: Ubuntu
- User OS & Browser: Ubuntu, Firefox

**Comment by marefr** [comment]
Would recommend upgrading Image Renderer Service to v2.0.0 (latest version). 

Suggests enabling debug/verbose logs, see https://github.com/grafana/grafana-image-renderer/blob/master/docs/remote_rendering_using_docker.md#environment-variables

f using environment variables, use:
```
LOG_LEVEL=debug
RENDERING_VERBOSE_LOGGING=true
RENDERING_DUMPIO=true
```

You could as an alternative mount a configuration file in the container, for instructions see https://github.com/grafana/grafana-image-renderer/blob/master/docs/remote_rendering_using_docker.md#configuration-file

Let us know how this works.

**Comment by Ma27** [comment]
* We're not using v1.0.0 there, but instead a fairly recent `master` (ce1f81438e5f69c7fd7c73ce08bab624c4c92e25).
* The issue disappears as soon as we comment out `root_url`. I confirmed that using `http` or `https` doesn't make a difference. Also, setting and unsetting the hostname from `root_url` (see above for the config snippet) to `127.0.0.1` in `/etc/hosts` doesn't make a difference as well.
* As requested, I ran the service yesterday with more verbose logs enabled: https://gist.github.com/Ma27/51fd65d8a2182c5a0c5e8855d956e2fc

Now I'm not experienced with the internals of how this plugin works. Do those additional things help you to comprehend this issue or is there anything else I can do? :)

**Comment by itobey** [comment]
I have the exact same issue. I'm using the setup in almost the entirely same way on a cloud server and on a home server. The difference beeing that Grafana on the cloud server is behind an nginx, so I do use the root_url there. I do not on my home server however.
On the cloud server I see the same results as @Ma27. On my home server everything works as expected. So the culprit must be root_url. Unfortunately removing root_url is no option for me.

Images used are:
grafana/grafana:7.3.3
grafana/grafana-image-renderer:2.0.1

**Comment by kvz** [comment]
In our (@Ma27’s and my) case it is behind HAProxy so this may be related. I think we modify the URL as we pass it down to Grafana (we strip a /grafana prefix that is just there to tell HAProxy to which backend to route the traffic (and be able to host multiple services on that host easily) we use the root_url so that working (valid host and the /grafana prefixed) URLs are returned in Alerts.

**Comment by marefr** [comment]
@kvz then it sounds like you don't want to have serve_from_sub_path=true

**Comment by kvz** [comment]
Wow, that fixed it, thank you so much, and sorry for wasting your time over a misconfiguration on our part :ok_hand:
