### ISSUE TITLE
Panels are not using the selected timezone from the url query

### ISSUE THREAD

**Issue by Bujupah** [grafana/grafana-image-renderer#223]
**Environment**:
- Grafana Image Renderer version: 2.1.1
- Grafana version: 7.3.1
- Installed plugin or remote renderer service: Remote
- OS Grafana Image Renderer is installed on: Windows/Linux
- User OS & Browser: Windows/Linux | Chromium/Chrome

**Issue**:
I tried rendering a panel with a given TZ as query param
http://localhost:3000/render/d-solo/DRoB8klMk/_?orgId=1&panelId=20&width=1000&height=500&tz=Africa/Tunis

Fully aware that the timezone format should be in this list [ICUs metaZones.txt](https://source.chromium.org/chromium/chromium/src/+/master:third_party/icu/source/data/misc/metaZones.txt)

but it seems like it was always falling back to host machine TZ and the puppeteer is not using the TimeZone from the env.TZ value...

**config.json file**:
```json
{
   ...
  "rendering": {
    "chromeBin": null,
    "args": [
      "--no-sandbox"
    ],
    "ignoresHttpsErrors": true,

    "timezone": null,
    "acceptLanguage": null,
    "width": 1000,
    "height": 500,
    "deviceScaleFactor": 1,
    "maxWidth": 3080,
    "maxHeight": 3000,
    "maxDeviceScaleFactor": 3,

    "mode": "default",
    "clustering": {
      "mode": "clustered",
      "maxConcurrency": 10
    },

    "verboseLogging": false,
    "dumpio": false
  }
}
```

**Comment by Bujupah** [comment]
Will raise a PR for a fix

**Comment by Bujupah** [comment]
PR #224

**Comment by Bujupah** [comment]
@marefr @torkelo @aknuds1 some check this out please 🔢 
Want to know if I am using tz wrongly

**Comment by AgnesToulet** [comment]
Closed by https://github.com/grafana/grafana-image-renderer/pull/224
