### ISSUE TITLE
Configuration: Add a setting to override puppeteer-cluster timeout 

### ISSUE THREAD

**Issue by AgnesToulet** [grafana/grafana-image-renderer#279]
**What would you like to be added**:
Add a new configuration field to override the default timeout for the `clustered` mode.

**Why is this needed**:
Each rendering request can send a [timeout option](https://github.com/grafana/grafana-image-renderer/blob/master/src/browser/browser.ts#L25) that will be used when navigating to a page, waiting for panels to be rendered or taking a sreenshot.
However, in `clustered` mode, a timeout of 30 seconds is already set when launching the cluster (see https://github.com/thomasdondorf/puppeteer-cluster#clusterlaunchoptions). So, even if the request timeout is over 30 seconds, the rendering request will be stopped after 30 seconds by the underlying cluster library.

**Comment by Bujupah** [comment]
I am facing an issue with timeout related to puppeteer-cluster 

```
Error: Timeout hit: 30000
    at Object.<anonymous>(/usr/src/app/node_modules/puppeteer-cluster/dist/util.js:69:23)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/src/app/node_modules/puppeteer-cluster/dist/util.js:5:58)
    at runNextTicks (internal/process/task_queues.js:60:5)
    at listOnTimeout (internal/timers.js:526:9)
    at processTimers (internal/timers.js:500:7)"
```

I tried to increase it to 60s but same issue is appearing... 
Any idea what could be the reason?
is there any suggested value for that timeout?
