### ISSUE TITLE
Plugin disabled due to modified content

### ISSUE THREAD

**Issue by jgarciadelanoceda** [grafana/grafana-image-renderer#304]
**What happened**:
We installed last Grafana (8.2.2) version in a Windows Server and we installed this plugin using admin/plugins.
We observed that when we stop the Windows Grafana Service sometimes we find this message
![image](https://user-images.githubusercontent.com/6615999/141323142-aae4fa84-69c2-4832-9535-f5734e3ec1de.png)

**What you expected to happen**:
To do not have problems when restarting grafana service

**How to reproduce it (as minimally and precisely as possible)**:

Have a Grafana service in a Windows machine with this plugin installed. Restart the service several times.

**Anything else we need to know?**:

**Environment**:
- Grafana Image Renderer version:3.2.1
- Grafana version:8.2.2
- Installed plugin or remote renderer service:Installed plugin
- OS Grafana Image Renderer is installed on:Windows
- User OS & Browser:Chrome
- Others:

**Comment by Maplesoup** [comment]
+1 to this, getting the same issue. 

If installed via cli grafana won't even start

**Comment by mattkosonen** [comment]
Same issue here. I have it installed on a Windows machine as well.

**Comment by Maplesoup** [comment]
Quick fix for this is to install 3.2.0 instead. If you are using the grafana cli you can add a version as the last arguement for the install command.

**Comment by AgnesToulet** [comment]
Hello! Thank you for reporting this. Can you share your Grafana logs when restarting Grafana and seeing the plugin disabled?
Also, it's very surprising that downgrading to 3.2.0 is fixing the issue, @Maplesoup could you try the latest plugin version as well please? (3.3.0)

**Comment by jgarciadelanoceda** [comment]
Hello,

I reproduce it again with version 3.3.0 (I did not tried to do it with version 3.2.0 though)

I attach you the log
[grafana.log](https://github.com/grafana/grafana-image-renderer/files/7625700/grafana.log)

As you can see at 13:22 I installed the plugin via web.
At 13:24 I tried to render a image but as I did not stop Grafana to load the plugin it failed so I restarted Grafana at 13:25
At 13:26 I rendered an image and seconds later I rendered another but stop Grafana service.

You can see that at 13:27 grafana-image-renderer has a modified signature so the plugin does not start.

![image](https://user-images.githubusercontent.com/6615999/144048565-8ed64c35-302c-4f22-bc89-ad94db760c75.png)


Something that it is also noticiable is that if you download the zip File via grafana Api you get a folder named plugin-win32-x64-unknown that is something that is weird for me.

I download all the plugins via this script(It is a Powershell file but you can see the logic inside)

[DownloadPlugins.txt](https://github.com/grafana/grafana-image-renderer/files/7625761/DownloadPlugins.txt)

**Comment by jgarciadelanoceda** [comment]
@AgnesToulet  info already added

**Comment by AgnesToulet** [comment]
Thanks for the logs! This is the same issue as https://github.com/grafana/grafana-image-renderer/issues/260 and it's fixed in Grafana 9.4.0 (https://github.com/grafana/grafana/pull/59104).
