### ISSUE TITLE
Render current visualization type instead of the saved one

### ISSUE THREAD

**Issue by mjtrangoni** [grafana/grafana-image-renderer#307]
**What happened**:

I changed the panel visualization type from "Stat" to "Time series" and wanted to render this panel without saving the dashboard changes.

**What you expected to happen**:

A "Time series" graph image rendered.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a dashboard with one "Stat" Panel and save it.
2. Edit it and change the visualization type to "Time series".
3. Apply the changes without saving the dashboard.
4. Click on share panel, "Direct link rendered image", and you will get a render of a "Stat" panel

**Anything else we need to know?**:

I don't know if this is a render bug or it is more a Grafana implementation thing.

**Environment**:
- Grafana Image Renderer version: **v3.3.0**
- Grafana version: **v8.2.4**
- Installed plugin or remote renderer service: Installed plugin
- OS Grafana Image Renderer is installed on: CentOS 8.4
- User OS & Browser: Windows 10, Chrome v96.0.4664.45

**Comment by AgnesToulet** [comment]
Hi, thank you for reporting this but this is working as expected. Dashboard has to be saved for the image renderer to access the panel information. When the dashboard is not saved, the new panel information is only available in your browser.
