### ISSUE TITLE
Doesn't seem to work with new alert manager (Webhook response status 400 Bad Request)

### ISSUE THREAD

**Issue by MatthewScholefield** [grafana/grafana-image-renderer#309]
**What happened**:

The image renderer doesn't seem to work after upgrading grafana to 8.3.3 and [opting in](https://grafana.com/docs/grafana/latest/alerting/unified-alerting/opt-in/) to the new alert manager (note: it is the default for new installs).

**What you expected to happen**:

Images to show in telegram alert notifications.

**How to reproduce it (as minimally and precisely as possible)**:

1. Setup latest grafana and grafana image renderer in separate docker containers as described in the docs
2. Make sure the new alerts system is enabled
3. Trigger an alert

**Anything else we need to know?**:

I tried an alert with and without a panel and both didn't work. I noticed the following in the grafana logs which could be related:
```
my-service-grafana-1  | t=2021-12-15T13:42:01+0000 lvl=eror msg="Failed to send webhook" logger=alerting.notifier.telegram error="Webhook response status 400 Bad Request" webhook="Telegram - Alert Notifier"
my-service-grafana-1  | t=2021-12-15T13:42:01+0000 lvl=info msg="level=error component=dispatcher msg=\"Notify for alerts failed\" num_alerts=3 err=\"Telegram - Alert Notifier/telegram[0]: notify retry canceled due to unrecoverable error after 1 attempts: Webhook response status 400 Bad Request\"" logger=alertmanager org=1
```

**Environment**:
- Grafana Image Renderer version: 3.3.0
- Grafana version: 8.3.3
- Installed plugin or remote renderer service: Remote renderer service
- OS Grafana Image Renderer is installed on: [Docker](https://hub.docker.com/r/grafana/grafana-image-renderer)
- User OS & Browser: n/a

**Comment by AgnesToulet** [comment]
Hello! This is actually not a bug, this is the intended behavior of the new alerting feature. You can find more context about this here: https://github.com/grafana/grafana/discussions/41015#discussioncomment-1548846
