### ISSUE TITLE
Rendering failed with "error=dial tcp :0: connect: connection refused"

### ISSUE THREAD

**Issue by rtoenniges** [grafana/grafana-image-renderer#311]
**What happened**:
After updating Grafana to v8.3.3 the "Image renderer plugin" doesn't work anymore.

I've enabled/increased every logging option i've found but this is all information I could get:
`t=2021-12-23T15:04:11+0100 lvl=info msg=Rendering logger=rendering renderer=plugin path="d-solo/R8ariy4nk/virtual-machines?orgId=1&refresh=1m&from=1640257253745&to=1640268053746&panelId=7&width=1000&height=500&tz=Europe%2FBerlin"
t=2021-12-23T15:04:11+0100 lvl=eror msg="Rendering failed." logger=context userId=1 orgId=1 uname=admin error="dial tcp :0: connect: connection refused"
t=2021-12-23T15:04:11+0100 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/render/d-solo/R8ariy4nk/virtual-machines status=500 remote_addr=192.168.2.40 time_ms=2 size=1344 referer=
`

**How to reproduce it (as minimally and precisely as possible)**:
It happens everytime I want to render a graph via "share" and "alert".

**Anything else we need to know?**:
The plugin is listening correctly
`tcp   LISTEN 0      128        127.0.0.1:43513      0.0.0.0:*    users:(("plugin_start_li",pid=10381,fd=19)) `

I've tried to set the IP and Port to "0.0.0.0:8080" which works fine but the error is still the same.

Grafana is installed directly and not in a docker.
In grafana.ini all render plugin options are set to default.

I've also disabled SELinux and firewalld temporarely but with no effect.

**Environment**:
- Grafana Image Renderer version: 3.3.0
- Grafana version: 8.3.3
- Installed plugin or remote renderer service: plugin
- OS Grafana Image Renderer is installed on: AlmaLinux 8
- User OS & Browser: Windows 11 / Chrome

**Comment by BAStos525** [comment]
same problem here:
`dial tcp 10.43.161.26:8081: connect: connection refused"`
`error="failed to send request to remote rendering service`
Grafana v 8.4.5
Image Rendeder v 3.4.2 (latest)
Kubernetes deployment through Grafana Helm Chart. default settings (worked on previous grafana version 8.3)

**Comment by kogent** [comment]
there was a [shared library](https://grafana.com/docs/grafana/latest/image-rendering/troubleshooting/#missing-libraries) added to the dependencies that we missed `libxshmfence1` after that things started working again.

**Comment by AgnesToulet** [comment]
Hi! Is this issue still present with latest Grafana and image renderer? Does the suggestion above solve your issue?

**Comment by AgnesToulet** [comment]
Hello! Closing this issue as there was no update for a few weeks. Feel free to reach out if you're still experiencing it and I'll re-open it.
