### ISSUE TITLE
config.json - how?

### ISSUE THREAD

**Issue by sanchomuzax** [grafana/grafana-image-renderer#313]
**What happened**: I can’t set a custom config file on my system. The Image renderer plugin works. However, if I create a `config.json` file (and restart the Grafana service), the Image Renderer plugin will not work. It will only work again if I reinstall the plugin.

I would like to change the default language to Hungarian, because the plugin is render all numbers in not my country’s format. I read the documentation. I don’t understand that how could I set up the `config.json` if I don’t use Docker? I don’t need to start a plugin service, it runs anyway, but I can’t found the usage of the config.json.

What is the problem?

**Environment**:
- Grafana Image Renderer version: v3.3.0
- Grafana version: v8.3.2
- OS Grafana Image Renderer is installed on: CentOS

**Comment by AgnesToulet** [comment]
Hi! It seems like you are running the image renderer in plugin mode. In plugin mode, you can't use the `config.json`, you need to update the plugin configuration through the Grafana configuration. You'll find all the available options here: https://grafana.com/docs/grafana/latest/administration/configuration/#plugingrafana-image-renderer

In the documentation, it's explained at the begining of this section: https://grafana.com/docs/grafana/latest/image-rendering/#configuration. I'd be interested to know if you didn't find the right section in the documentation or if it didn't make sense so we can improve it.

**Comment by sanchomuzax** [comment]
Thank you for your reply!

> ... you need to update the plugin configuration through the Grafana configuration

I added the following lines to the `/etc/grafana/grafana.ini` file, and restart the service of Grafana, but no changes.

`[plugin.grafana-image-renderer]`
`rendering_language = 'hu-HU,hu;q=0.8,en-US;q=0.5,en;q=0.3'`

I used local format to A-series:

![image](https://user-images.githubusercontent.com/2911588/148576232-8139ea22-6d61-4c91-b99b-cca787161005.png)

The rendered image is not used the Hungarian location format:

![image](https://user-images.githubusercontent.com/2911588/148576295-64349a87-b685-4e17-983b-0e94e56caf55.png)

**Comment by sanchomuzax** [comment]
> Hello!
> 
> Investigating this issue, I noticed than if I do this request in my browser, it doesn't work because I have the following header set `Accept-Language:en-US,en;q=0.9` but when I do the request via cURL without the header set, the following configuration works fine:
> 
> ```
> [plugin.grafana-image-renderer]
> rendering_language = fr-FR
> ```
> 
> Closing this issue as it's quite old and the feature seems to be working as expected. Please reach out if the issue is still there.

I tested it again. Unfortunately, the solution you suggested does not work.

However, I changed the corresponding line of the /etc/grafana/grafana.ini file to this:

~~~
[plugin.grafana-image-renderer]
rendering_language = hu-HU
~~~

After:

~~~
systemctl restart grafana-server
~~~

Numbers on the web output:

![image](https://github.com/grafana/grafana-image-renderer/assets/2911588/62577a77-8643-40ce-bc37-e221b21467bc)

Numbers on the rendered image:

![image](https://github.com/grafana/grafana-image-renderer/assets/2911588/276753fc-d261-47ce-a5ff-e97010024403)

Grafana version: v8.5.15 (be4228db5a)

**Comment by AgnesToulet** [comment]
Hi! Could you look into your browser dev console when you're rendering the image and check that the `Accept-Language` header is not provided?

**Comment by sanchomuzax** [comment]
`Accept-Language: hu,en;q=0.9,en-GB;q=0.8,en-US;q=0.7`

**Comment by sanchomuzax** [comment]
I can found the solution:

Insert the following lines to the `/usr/lib/systemd/system/grafana-server.service`

~~~
[Service]
Environment="LANG=hu_HU.UTF-8"
~~~

And after:

~~~
sudo systemctl daemon-reload
sudo systemctl restart grafana-server
~~~

The rendered image is using the `hu-HU` language number's formats.

Solved, tnx! You can close it. 👍
