### ISSUE TITLE
service=*rendering.RenderingService reason="Unrecognized remote plugin message

### ISSUE THREAD

**Issue by simPod** [grafana/grafana-image-renderer#334]
**What happened**:

> EROR[03-10|09:17:04] Stopped background service               logger=server service=*rendering.RenderingService reason="Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to be recompiled to support the latest protocol."

Same as in https://github.com/grafana/grafana-image-renderer/issues/323 however I'm on macos. Is there something specific to the platform?

**Environment**:
- Grafana Image Renderer version: 3.4.1
- Grafana version: https://github.com/grafana/grafana/commit/9fc9708ba5e9ee0f0565c00e681d2bf19146cee0
- Installed plugin or remote renderer service: ?
- OS Grafana Image Renderer is installed on: macos
- User OS & Browser: macos
- Others:

**Comment by ArturWierzbicki** [comment]
Hey @simPod, thanks for reporting the issue! 

Are you using an M1 or an Intel Mac? If it's Intel, can you please run `./REPLACE_WITH_PATH_TO_PLUGINS_DIR/grafana-image-renderer/plugin_start_darwin_amd64` and let us know the output?

**Comment by simPod** [comment]
@ArturWierzbicki it's intel

```
Error: This binary is a plugin. These are not meant to be executed directly. Please execute the program that consumes these plugins, which will load any plugins automatically
    at /snapshot/grafana-image-renderer/build/node-plugin/lib/server.js:85:15
    at Generator.next (<anonymous>)
    at /snapshot/grafana-image-renderer/build/node-plugin/lib/server.js:8:71
    at new Promise (<anonymous>)
    at /snapshot/grafana-image-renderer/build/node-plugin/lib/server.js:4:12
    at serve (/snapshot/grafana-image-renderer/build/node-plugin/lib/server.js:78:25)
    at /snapshot/grafana-image-renderer/build/app.js:46:43
    at Generator.next (<anonymous>)
    at /snapshot/grafana-image-renderer/build/app.js:8:71
    at new Promise (<anonymous>)
```

**Comment by simPod** [comment]
However, I'm not seeing the error now 🤔 What could have happened?

**Comment by ArturWierzbicki** [comment]
@simPod 
> However, I'm not seeing the error now thinking What could have happened?

Hmm.. honestly I am not sure - I was expecting to see a different error in the output of `./REPLACE_WITH_PATH_TO_PLUGINS_DIR/grafana-image-renderer/plugin_start_darwin_amd64`. The error you pasted is expected, it doesn't indicate that there are any issues with running the plugin. Is it possible you were running some old, cached version of the IR plugin before?

**Comment by simPod** [comment]
No, I explicitly tried to uninstall and install. Weird. Anyways, thanks for help. Will come back if I stumble across it again ;)
