### ISSUE TITLE
broken link on dockerhub

### ISSUE THREAD

**Issue by Gornoka** [grafana/grafana-image-renderer#341]
**What happened**:
link on dockerhub to image renderer is linking to a removed markdown file.
![image](https://user-images.githubusercontent.com/45569834/160244130-2bef23a8-ee19-4478-800b-32f72b0432c1.png)
lower link in the picture targets [/docs/remote_rendering_using_docker.md](https://github.com/grafana/grafana-image-renderer/blob/master/docs/remote_rendering_using_docker.md)
which no longer exists

**What you expected to happen**:
just link to the main readme, since this includes the instruction for docker / docker-compose deploy.
(https://github.com/grafana/grafana-image-renderer)

**How to reproduce it (as minimally and precisely as possible)**:
1. go to dockerhub [https://hub.docker.com/r/grafana/grafana-image-renderer](https://hub.docker.com/r/grafana/grafana-image-renderer)
2. second link in second paragraph 
![image](https://user-images.githubusercontent.com/45569834/160244247-567f6648-55bc-4c83-ad56-0069069c195c.png)
3. enjoy githubs 404 page

**Anything else we need to know?**:
thanks for the great software

With kind Regards
Lukas

**Comment by AgnesToulet** [comment]
Thank you for reporting this! It's updated with a proper link now.
