### ISSUE TITLE
[net::ERR_CERT_AUTHORITY_INVALID] rendering_ignore_https_errors is not working

### ISSUE THREAD

**Issue by kubosuke** [grafana/grafana-image-renderer#345]
**What happened**:

rendering_ignore_https_errors option is not working if I set below values in grafana ini file:

```
[plugin.grafana-image-renderer]
rendering_ignore_https_errors = true
```

**What you expected to happen**:

able to access https://localhost:33333/d-solo/LYLqfglGk/${DASHBOARD_NAME} if cert authority is invalid

**How to reproduce it (as minimally and precisely as possible)**:

1. apply the self-signed certificate to grafana server (actually there is Nginx proxy server in front of Grafana)
2. access to render link /render/d-solo/LYLqfglGk/${DASHBOARD_NAME}

**Anything else we need to know?**:

**Environment**:
- Grafana Image Renderer version:

```
/grafana-cli --pluginsDir /home/user/usr/grafana/plugins/ plugins ls
installed plugins:
grafana-image-renderer @ 2.1.1
```

- Grafana version:

```
./grafana-server -v
Version 6.7.6 (commit: 86c5fe3746, branch: HEAD)
```

- Installed plugin or remote renderer service:
- OS Grafana Image Renderer is installed on:

```
cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
```

- User OS & Browser:
- Others:

![Untitled Diagram](https://user-images.githubusercontent.com/40480197/167601456-10cd72d4-1b74-46b6-9a68-00221bb6aa76.jpg)

**Comment by kubosuke** [comment]
sorry, it start working when I specify 

```
 [rendering]
server_url
rendering_ignore_https_errors
```

**Comment by fanlifei** [comment]
renderer      | {"err":"Error: net::ERR_CERT_AUTHORITY_INVALID at https://grafana:3000/grafana/d-solo/afqgNw17z2/home?orgId=1&from=1666925192192&to=1666926092192&panelId=16&width=1000&height=500&tz=Asia%2FShanghai&render=1\n    at navigate (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:156:23)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async FrameManager.navigateFrame (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:131:21)\n    at async Frame.goto (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:512:16)\n    at async Page.goto (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1167:16)\n    at async Browser.takeScreenshot (/usr/src/app/build/browser/browser.js:256:13)\n    at async Browser.render (/usr/src/app/build/browser/browser.js:230:20)\n    at async HttpServer.render (/usr/src/app/build/service/http-server.js:53:28)","level":"error","message":"Error while trying to prepare page for screenshot","url":"https://grafana:3000/grafana/d-solo/afqgNw17z2/home?orgId=1&from=1666925192192&to=1666926092192&panelId=16&width=1000&height=500&tz=Asia%2FShanghai&render=1"}
renderer      | {"err":"TimeoutError: waiting for function failed: timeout 60000ms exceeded\n    at new WaitTask (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:528:34)\n    at DOMWorld.waitForFunction (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:479:26)\n    at Frame.waitForFunction (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:1010:32)\n    at Page.waitForFunction (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2490:33)\n    at /usr/src/app/build/browser/browser.js:284:29\n    at Browser.withTimingMetrics (/usr/src/app/build/browser/browser.js:411:20)\n    at Browser.takeScreenshot (/usr/src/app/build/browser/browser.js:280:24)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Browser.render (/usr/src/app/build/browser/browser.js:230:20)\n    at async HttpServer.render (/usr/src/app/build/service/http-server.js:53:28)","level":"error","message":"Error while waiting for the panels to load","url":"https://grafana:3000/grafana/d-solo/afqgNw17z2/home?orgId=1&from=1666925192192&to=1666926092192&panelId=16&width=1000&height=500&tz=Asia%2FShanghai&render=1"}
