### ISSUE TITLE
CSV rendering is failing when using other languages as filename

### ISSUE THREAD

**Issue by Bujupah** [grafana/grafana-image-renderer#353]
**What happened**:
When generating a CSV file with another language like Thai, renderer fails to give back a response.

**What you expected to happen**:
Using any language in CSV filename, rendering should work.

**How to reproduce it (as minimally and precisely as possible)**:
Render a csv giving it a filename written in Thai 

**Anything else we need to know?**:

**Environment**:
- Grafana Image Renderer version: latest 
- Grafana version: any
- Installed plugin or remote renderer service: remote
- OS Grafana Image Renderer is installed on: Linux | Windows
- User OS & Browser: Chrome | Edge
- Others:

**Comment by Bujupah** [comment]
```ts
   const result = await this.browser.renderCSV(options);

    if (result.fileName) {
      // This line of code is causing the failure
      // This will throw an error when using Thai language for example as fileName
      // ERROR: Invalid character in header content ["Content-Disposition"]
      res.setHeader('Content-Disposition', `attachment; filename="${result.fileName}"`); 
    }
    res.sendFile(result.filePath, (err) => {
```

**Comment by Bujupah** [comment]
```ts
   const result = await this.browser.renderCSV(options);

    if (result.fileName) {
      // I think using encodeURIComponent will solve this.
      res.setHeader('Content-Disposition', `attachment; filename="${encodeURIComponent(result.fileName)}"`); 
    }
    res.sendFile(result.filePath, (err) => {
```

**Comment by spinillos** [comment]
This issue was fixed and will be in the next release. 

Code: https://github.com/grafana/grafana-image-renderer/blob/master/src/service/http-server.ts#L238
