### ISSUE TITLE
How do I specify the value of a dashboard variable in a url when calling grafana-image-renderer?

### ISSUE THREAD

**Issue by rcowham** [grafana/grafana-image-renderer#383]
**What would you like to be added**:

I would like it to be implemented/documented how to render a specific Grafana dashboard panel when its containing dashboard has variables (and I want to render with something other than the default value of the variable!)

**Why is this needed**:

For automation of reports where there are variables in the containing dashboard.

**Comment by joanlopez** [comment]
Hi @rcowham,

Have you tried to specify the values of those variables in the URL?
It should work by passing the variables as URL parameters with the prefix `var`, like:
`<url-to-your-dashboard>?var-host=myhost` - for a `host` variable.

Thanks!

**Comment by rcowham** [comment]
Thanks - that works.
