### ISSUE TITLE
ERR_CERT_AUTHORITY_INVALID with docker image and grafana using https

### ISSUE THREAD

**Issue by rbuffi** [grafana/grafana-image-renderer#384]
With grafana-image-renderer (latest) docker image working with grafana 9.2 instance that is using https we get  ERR_CERT_AUTHORITY_INVALID.  We are also using docker version of grafana-enterprise. Ignoring https errors does not seem to help setting the grafana image-renderer environment variables.

**Comment by rbuffi** [comment]
This was the solution! Thank you !

**Comment by joanlopez** [comment]
> This was the solution! Thank you !

Glad to read!
