### ISSUE TITLE
Scaling dashboard

### ISSUE THREAD

**Issue by kaffarell** [grafana/grafana-image-renderer#385]
**What would you like to be added**:
Is there a way to scale the dashboard? We want to render a dashboard in 1920x1080 but have the font bigger (of the titles etc). Sames as if you would press Ctrl+ in grafana on a dashboard. We found the scale option but it just seems to affect the resolution and not make the actual content bigger.

**Why is this needed**:
We want to display grafana dashboards on LFDs and need them to be bigger so they can be readable from a distance.

**Comment by kaffarell** [comment]
There is this issue open on puppeteer https://github.com/puppeteer/puppeteer/issues/4419

**Comment by joanlopez** [comment]
> There is this issue open on puppeteer [puppeteer/puppeteer#4419](https://github.com/puppeteer/puppeteer/issues/4419)

Looks like that issue has been closed, although not sure if the suggested solutions are valid alternatives to what you did on #387 or if we can just go straight with your approach 🤔  Thanks!
