### ISSUE TITLE
Review Image Renderer settings coherency (standalone vs plugin) 

### ISSUE THREAD

**Issue by joanlopez** [grafana/grafana-image-renderer#392]
**What happened**:

As mentioned [here](https://github.com/grafana/grafana-image-renderer/issues/342#issuecomment-1369011995), certain configuration settings are only available when the Image Renderer is deployed as gRPC plugin but not when running it as standalone application, with no apparent reason.

So, would be good to review all of them and evaluate which (if any) should be supported as well when running the Image Renderer as a standalone application, and fix them.

**What you expected to happen**:

Review Image Renderer settings to be "coherent" between standalone and plugin modes, unless there's a reason to don't do it.

**How to reproduce it (as minimally and precisely as possible)**:

N/A

**Anything else we need to know?**: N/A

**Environment**: 
- Grafana Image Renderer version: _N/A_
- Grafana version: _N/A_
- Installed plugin or remote renderer service: _N/A_
- OS Grafana Image Renderer is installed on: _N/A_
- User OS & Browser: _N/A_
- Others: _N/A_

**Comment by AgnesToulet** [comment]
Hi @joanlopez!

Actually, all the settings are available in standalone mode through the [config.json](https://github.com/grafana/grafana-image-renderer/blob/master/default.json) file. But I agree that settings management is currently a bit messy and it could be worth to improve it.

The reverse (settings available in standalone mode and not through plugin env variable) is a real problem though, see https://github.com/grafana/grafana-image-renderer/issues/317.

**Comment by joanlopez** [comment]
> But I agree that settings management is currently a bit messy and it could be worth to improve it.

Yeah, honestly I didn't go very deep on what is available on each (plugin vs standalone), and what can be configured with different mechanisms (config file, environment variables, etc), but I agree the goal of this issue should be to improve the settings management in general.

I probably mis-explained it, but iirc what I was thinking when I said that a certain setting is not available on the standalone mode was more specifically that _you cannot configure/override it through environment variables_, or at least I guess some settings should be [here](https://github.com/grafana/grafana-image-renderer/blob/master/src/app.ts#LL96C10-L96C38) to make that possible.

In any case, sorry for the vague description, and happy to see that we're aligned (there's lot of room for improvements on settings' management) :)
