### ISSUE TITLE
Grafana Image Renderer | 3.5.0 | ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by utsukprani** [grafana/grafana-image-renderer#393]
**What happened**:
I am trying to create custom grafana image with pre-installed Grafana Image Render plugin.
I have grafana 7.5.3 and I used the following Grafana Docker file as suggested on github
[Dockerfile](https://github.com/grafana/grafana/blob/main/packaging/docker/custom/Dockerfile)

As per documentation of grafana image render, I used the version 3.5.0 url in the --pluginUrl within the Dockerfile, which is compatible with grafana 7.5.3.
[Grafana Image Renderer v3.5.0](https://github.com/grafana/grafana-image-renderer/releases/download/v3.5.0/plugin-linux-x64-glibc-no-chromium.zip)

**What you expected to happen**:
I expected the image rendering plugin to work.

**How to reproduce it (as minimally and precisely as possible)**:
- Create custom grafana docker image by using the above Dockerfile and image renderer pluginUrl
- Run grafana
- open a dashboard
- Share a panel
- Click on the Direct link rendered image

We get the below error message and the rendering fails 
`t=2023-01-06T07:23:30+0000 lvl=eror msg="Browser request failed" logger=plugins.backend pluginId=grafana-image-renderer url="https://localhost:3000/d-solo/Nrr-mqpVk/atomiq-diagnostics-kpi?orgId=1&refresh=1m&from=1672817004987&to=1672989804987&panelId=48&width=1000&height=500&tz=Asia%2FCalcutta&render=1" method=GET failure=net::ERR_CERT_AUTHORITY_INVALID
t=2023-01-06T07:23:30+0000 lvl=eror msg="Error while trying to prepare page for screenshot" logger=plugins.backend pluginId=grafana-image-renderer url="https://localhost:3000/d-solo/Nrr-mqpVk/atomiq-diagnostics-kpi?orgId=1&refresh=1m&from=1672817004987&to=1672989804987&panelId=48&width=1000&height=500&tz=Asia%2FCalcutta&render=1" err="Error: net::ERR_CERT_AUTHORITY_INVALID at https://localhost:3000/d-solo/Nrr-mqpVk/atomiq-diagnostics-kpi?orgId=1&refresh=1m&from=1672817004987&to=1672989804987&panelId=48&width=1000&height=500&tz=Asia%2FCalcutta&render=1\n    at navigate (/snapshot/grafana-image-renderer/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:156:23)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async FrameManager.navigateFrame (/snapshot/grafana-image-renderer/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:131:21)\n    at async Frame.goto (/snapshot/grafana-image-renderer/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:512:16)\n    at async Page.goto (/snapshot/grafana-image-renderer/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1167:16)\n    at async Browser.takeScreenshot (/snapshot/grafana-image-renderer/build/browser/browser.js:256:13)\n    at async Browser.render (/snapshot/grafana-image-renderer/build/browser/browser.js:230:20)\n    at async PluginGRPCServer.render (/snapshot/grafana-image-renderer/build/plugin/v2/grpc_plugin.js:107:13)"
t=2023-01-06T07:24:29+0000 lvl=info msg="Rendering timed out" logger=rendering renderer=plugin
t=2023-01-06T07:24:29+0000 lvl=eror msg="timeout error - you can set timeout in seconds with &timeout url parameter" logger=context userId=1 orgId=1 uname=admin error="timeout error - you can set timeout in seconds with &timeout url parameter"
t=2023-01-06T07:24:29+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/render/d-solo/Nrr-mqpVk/atomiq-diagnostics-kpi status=500 remote_addr=10.197.176.121 time_ms=62036 size=1784 referer=
t=2023-01-06T07:24:30+0000 lvl=eror msg="Error while waiting for the panels to load" logger=plugins.backend pluginId=grafana-image-renderer url="https://localhost:3000/d-solo/Nrr-mqpVk/atomiq-diagnostics-kpi?orgId=1&refresh=1m&from=1672817004987&to=1672989804987&panelId=48&width=1000&height=500&tz=Asia%2FCalcutta&render=1" err="TimeoutError: waiting for function failed: timeout 60000ms exceeded\n    at new WaitTask (/snapshot/grafana-image-renderer/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:528:34)\n    at DOMWorld.waitForFunction (/snapshot/grafana-image-renderer/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:479:26)\n    at Frame.waitForFunction (/snapshot/grafana-image-renderer/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:1010:32)\n    at Page.waitForFunction (/snapshot/grafana-image-renderer/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2479:33)\n    at /snapshot/grafana-image-renderer/build/browser/browser.js:284:29\n    at Browser.withTimingMetrics (/snapshot/grafana-image-renderer/build/browser/browser.js:396:20)\n    at Browser.takeScreenshot (/snapshot/grafana-image-renderer/build/browser/browser.js:280:24)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async Browser.render (/snapshot/grafana-image-renderer/build/browser/browser.js:230:20)\n    at async PluginGRPCServer.render (/snapshot/grafana-image-renderer/build/plugin/v2/grpc_plugin.js:107:13)"
`

**Anything else we need to know?**:

**Environment**:
- Grafana Image Renderer version: 3.5.0
- Grafana version: 7.5.3
- Installed plugin or remote renderer service: Installed plugin
- OS Grafana Image Renderer is installed on:
- User OS & Browser: Red Hat Linux Enterprise Version 7.5. Browser - Chrome
- Others:

**Comment by utsukprani** [comment]
any suggestions ? recommendations ?

**Comment by spinillos** [comment]
Are you using `https` in Grafana and `http` in image-renderer? `ERR_CERT_AUTHORITY_INVALID` could mean and it doesn't allow you to access to Grafana urls from image-renderer. Its why you have timeouts when you try to render the page.

Under `[plugin.grafana-image-renderer]` you can set `rendering_verbose_logging = rendering:debug` to see more logs.

**Comment by Clarity-89** [comment]
Closing this for now, feel free to reopen if the issue persists.
