### ISSUE TITLE
plugin_start_linux_amd64 start script for linux missing

### ISSUE THREAD

**Issue by spike83** [grafana/grafana-image-renderer#4]
I've got the following error.

```
EROR[] Server shutdown                          logger=server reason="fork/exec .../grafana-image-renderer/plugin_start_linux_amd64: no such file or directory"
```
fixed it for me temporary by copy the `plugin_start_darwin_amd64` to `plugin_start_linux_amd64` which seems to work fine.

**Comment by torkelo** [comment]
Fixed

**Comment by jbondia** [comment]
Hi

I am seeing this error again with Grafana 7.5.4 and grafana-image-renderer 3.5.0

How did you fixed this issue?

Thanks
