### ISSUE TITLE
Does the notification's image rendering functionality supports to add path variables?

### ISSUE THREAD

**Issue by menes127** [grafana/grafana-image-renderer#408]
**What would you like to be added**:
Hi Grafana Team, I would like know how to set up a grafana alert with image renderer which is able to pass path variables.
for example, image URL may be like below
http://<grafana_host>/d/<Dashboard_UID>/<dashboard>?orgId=1&viewPanel=<Panel_ID>&**var-<path_variable>=<values>**

**Why is this needed**:
The image that is included in email alerts with default variables is not very helpful in determining the specific issues that occurred.

**Comment by joanlopez** [comment]
Hi @menes127,

I don't think what you're asking is Image Renderer's responsibility, but Grafana's, cause what the Image Renderer does is it just navigates to the provided URL. So, in such case, I think it should be Grafana, who provides the proper variable values in the URL when calling the Image Renderer service.

Could you create the issue in Grafana's repository, please?

Thanks!

**Comment by menes127** [comment]
Thanks, it's fine to close this issue ticket.
