### ISSUE TITLE
Reducing the dimentions of image

### ISSUE THREAD

**Issue by puneet336** [grafana/grafana-image-renderer#409]
I have created an automation through which i am "stitching" 4 graphs (downloading via requests) after changing FROM, TO in following URLs and sending them to email ( smtplib as html).

http://grafana-02:3003/render/d-solo/qEe_x5xVk/mydash1?orgId=1&from=_FROM_&to=_TO_&panelId=2&width=1000&height=500&tz=Asia%2FCalcutta

Here 's how the graph looks - 
![image](https://user-images.githubusercontent.com/5935825/221650189-2dad096c-557f-4968-8dfc-2261f855be05.png)

Problem is that these graphs are very big in size, and i have to unzoom upto 30% to see these graphs properly.

once i do width=100&height=50,  the image gets cropped - 
http://grafana-02:3003/render/d-solo/qEe_x5xVk/mydash1?orgId=1&from=_FROM_&to=_TO_&panelId=2&width=100&height=50&tz=Asia%2FCalcutta
, the graph does not get small, the image gets cropped , example - 
![image](https://user-images.githubusercontent.com/5935825/221651133-1b7a12c1-1e95-47f6-b665-c4a1023cf828.png)

Is there a way to reduce the dimentions of image through render api ? 
Please do let me know if i can provide you with any further information.

**Comment by puneet336** [comment]
I think there is a feature request already on this topic.
https://github.com/grafana/grafana/discussions/47211

**Comment by kaffarell** [comment]
You can also try to set a smaller width/height and then set a negative pageZoomLevel...

**Comment by AgnesToulet** [comment]
Closing this as stale as this was not updated for a while. Please feel free to re-open if the suggestions above did not solve your issue.
