### ISSUE TITLE
Unhandled Promise Rejection: Unknown Plugin type: renderer

### ISSUE THREAD

**Issue by jimmybrancaccio** [grafana/grafana-image-renderer#41]
**Update:**

I've actually got this working. It looks like I had a bunch of missing system libraries. Of note, I am on CentOS 7. Here's what got it working for me:

```
yum -y install libXcomposite libXtst cups-libs libXScrnSaver alsa-lib atk at-spi2-atk gtk3
```

**Original:**

Similar to #1, I cannot get the plugin to load properly. I am seeing this error in my browsers console:

`Unhandled Promise Rejection: Unknown Plugin type: renderer`

I am on a valid version of Grafana as far as I can tell, 6.4.1.

<img width="2556" alt="Screen Shot 2019-10-03 at 11 31 34 AM" src="https://user-images.githubusercontent.com/405585/66146024-898aa080-e5d1-11e9-9276-9334c9939fed.png">

<img width="1095" alt="Screen Shot 2019-10-03 at 11 31 43 AM" src="https://user-images.githubusercontent.com/405585/66146029-8becfa80-e5d1-11e9-9687-5b9f6540e564.png">

I did enable logging, but nothing stands out:

```
t=2019-10-03T11:30:33-0500 lvl=info msg="Renderer plugin found, starting" logger=rendering cmd=plugin_start_linux_amd64
t=2019-10-03T11:30:33-0500 lvl=dbug msg="starting plugin" logger=rendering path=/var/lib/grafana/plugins/grafana-image-renderer/plugin_start_linux_amd64 args=[/var/lib/grafana/plugins/grafana-image-renderer/plugin_start_linux_amd64]
t=2019-10-03T11:30:33-0500 lvl=dbug msg="plugin started" logger=rendering path=/var/lib/grafana/plugins/grafana-image-renderer/plugin_start_linux_amd64 pid=24558
t=2019-10-03T11:30:33-0500 lvl=dbug msg="waiting for RPC address" logger=rendering path=/var/lib/grafana/plugins/grafana-image-renderer/plugin_start_linux_amd64
t=2019-10-03T11:30:33-0500 lvl=info msg="Initializing Stream Manager"
t=2019-10-03T11:30:33-0500 lvl=info msg="HTTP Server Listen" logger=http.server address=127.0.0.1:3000 protocol=http subUrl= socket=
t=2019-10-03T11:30:34-0500 lvl=dbug msg="Renderer plugin started" logger=rendering
t=2019-10-03T11:30:34-0500 lvl=dbug msg="using plugin" logger=rendering version=1
```

Not sure where to go from here.

**Comment by marefr** [comment]
I will open an issue in grafana project regarding that loading the plugin description in UI doesn't work. 

Besides this feels like your problem is solved? Probably need to document the missing libraries somewhere.

**Comment by jimmybrancaccio** [comment]
@marefr I think that sounds like a good idea(both the opening issue with Grafana and updating the install docs). Yeah, my issue is resolved now. Thanks! :smile:
