### ISSUE TITLE
License Violations Detected!

### ISSUE THREAD

**Issue by AKhares** [grafana/grafana-image-renderer#410]
Hi Team,

In our recent scans we found the below 2 components flagged as license violations:
            Name                          Component
xvidcore/1.3.7-r1/x86_64	FFmpeg1.3.7	
unifont/15.0.01-r0/x86_64	unifont15.0.01	

Both these component’s license are GPL. We need to know how these components are being used in image renderer code?

Appreciate the Help.

Regards,
Amber Khare

**Comment by Clarity-89** [comment]
Those dependencies are not used in the image-renderer code, they probably come from the docker builds but have no relation to the image-renderer functionality.
