### ISSUE TITLE
There had a huge `core_files` generated. How do I stop this?

### ISSUE THREAD

**Issue by shezhangzhang** [grafana/grafana-image-renderer#422]
**What happened**:
<img width="234" alt="aaa" src="https://user-images.githubusercontent.com/26793777/234744183-cfe97523-8067-483a-9d7c-60ae3af0f6ab.png">
<img width="386" alt="bbb" src="https://user-images.githubusercontent.com/26793777/234744223-d4b01be4-9c1d-43fc-a8b3-8fb1a5224b2b.png">
when I am using this plugin in grafana, I found that there had a huge `core_files` generated. How do I stop this?

**What you expected to happen**:
No core_files.
**How to reproduce it (as minimally and precisely as possible)**:
just using this plugin and make some error when render a image.
**Anything else we need to know?**:

**Environment**:
- Grafana Image Renderer version: latest
- Grafana version: 9.2.2
- Installed plugin or remote renderer service: installed plugin
- OS Grafana Image Renderer is installed on: linux
- User OS & Browser: chrome latest
- Others: ..

**Comment by undef1nd** [comment]
Hello! I wonder if limiting core file size in `/etc/security/limits.conf` could help. Could you please give it a try? After making the change reboot the system for the new limit to take effect.

**Comment by shezhangzhang** [comment]
Sure, I have set the limit.conf to:
```bash
ulimit -c 0; \
```
Problem has been solved!
