### ISSUE TITLE
Please provide official ARM64 image

### ISSUE THREAD

**Issue by rickardp** [grafana/grafana-image-renderer#424]
**What would you like to be added**:
The image renderer compiles for ARM64 and building it cross platform with Docker is trivial. Please add ARM64 to the build pipelines so that an ARM64 version is always built and pushed with a release.

**Why is this needed**:
We want to use the official images instead custom-built images (which is error prone and takes time to maintain). We run mixed-arch Kubernetes clusters (Microsoft AKS in this case) and want all images  to be built for both architectures.
Local dev happens on Apple M1 machines to a large extent. It is useful to avoid emulation when running locally.

Generally, cloud computing is moving to ARM64 for cost reasons, so ARM64 is going to be more important than x64 in a very near future.

I would have attempted a pull request if this was built using GitHub Actions, but it looks like it's not (or at least not in this repo). I am not familiar with Drone, but if there is docker buildx support the fix should be trivial.

**Comment by AgnesToulet** [comment]
Closed by https://github.com/grafana/grafana-image-renderer/pull/468
