### ISSUE TITLE
Enabling alpha feature clientTokenRotation in Grafana causes grafana-image-renderer to fail calling the auth-token/rotate endpoint

### ISSUE THREAD

**Issue by wwalters12** [grafana/grafana-image-renderer#429]
**What happened**:
After enabling the [clientTokenRotation feature in Grafana](https://github.com/grafana/grafana/pull/65060), the grafana-image-renderer is failing to call the auth tokens/rorate endpoint. Seeing many errors like this in the grafana-image-renderer logs:
```
{"failure":"net::ERR_ABORTED","level":"error","message":"Browser request failed","method":"POST","url":"http://grafana-ha-stack.monitoring/api/user/auth-tokens/rotate"}
{"level":"error","message":"Browser console error","msg":"Failed to load resource: the server responded with a status of 401 (Unauthorized)","url":"http://grafana-ha-stack.monitoring/api/user/auth-tokens/rotate"}
```
We can see this error in the Grafana logs. 10.73.80.211 is the IP of the grafana-image-renderer pod:
```
logger=context userId=0 orgId=1 uname= t=2023-05-19T15:57:38.832349809Z level=error msg=Unauthorized error="invalid session token" remote_addr=10.73.80.211 traceID=
```

**What you expected to happen**:
grafana-image-renderer to not continuously fail calling the  auth-tokens/rotate endpoint.

**How to reproduce it (as minimally and precisely as possible)**:
Enable the alpha feature clientTokenRotation in Grafana.

**Anything else we need to know?**:
At this time I'm not sure if this is preventing the image renderer from working as we haven't made much use of it in our environment yet.

**Environment**:
- Grafana Image Renderer version: Latest, which is v3.7.1 at the time of this post
- Grafana version: v9.5.1
- Installed plugin or remote renderer service: Remote renderer service.
- OS Grafana Image Renderer is installed on: GKE
- Others: Grafana and image renderer are installed with v6 .17.10 of the [Grafana helm chart](https://github.com/grafana/helm-charts/tree/main/charts/grafana).

**Comment by Clarity-89** [comment]
@wwalters12 this should be fixed in Grafana 10.1: https://github.com/grafana/grafana/pull/68709.
