### ISSUE TITLE
Installing and running plugin in Grafana docker container doesn't work

### ISSUE THREAD

**Issue by scharissis** [grafana/grafana-image-renderer#43]
Rendering is not working on a fresh docker 'install' of Grafana 6.4.1 with grafana-image-renderer 1.0.5:

```
installing grafana-image-renderer @ 1.0.5
from: https://grafana.com/api/plugins/grafana-image-renderer/versions/1.0.5/download
into: /var/lib/grafana/plugins

✔ Installed grafana-image-renderer successfully 

...

t=2019-10-04T00:34:01+0000 lvl=eror msg="Rendering failed." logger=context userId=1 orgId=1 uname=admin error="Rendering failed: Error: Failed to launch chrome!\n/var/lib/grafana/plugins/grafana-image-renderer/chrome-linux/chrome: error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory\n\n\nTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md\n"
```

Installed/ran via docker as such:

```
docker run \
  -d \
  --user $(id -u) \
  --volume "$PWD/data:/var/lib/grafana" \
  -p 9001:3000 \
  --name=test-641 \
  -e "GF_INSTALL_PLUGINS=grafana-image-renderer,grafana-piechart-panel,grafana-worldmap-panel" \
  grafana/grafana:6.4.1
```

**Comment by jimmybrancaccio** [comment]
Perhaps related to #41?

**Comment by marefr** [comment]
@scharissis Thanks. What OS/system/architecture are you running docker from? Suggest you use PhantomJS for now as workaround or use the [remote rendering using docker](https://github.com/grafana/grafana-image-renderer#remote-rendering-using-docker). 

@jimmybrancaccio that's probably not related.

**Comment by sylarevan** [comment]
I have the same issue here. Grafana 6.4.1 running on Docker on a Synology NAS.

**Comment by scharissis** [comment]
@marefr 64-bit Ubuntu 18.04.3 LTS

```
$ uname -a
Linux x1c 4.15.0-64-generic #73-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ docker version
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:29:11 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:27:45 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by justClouds** [comment]
Just noticed the same error on my updated Docker container with 6.4.2...

**Comment by n1nj4888** [comment]
I have the same issue using the official grafana/grafana:latest docker image. I installed the grafana-image-renderer plugin via the grafana CLI as detailed in the official plugin docs and it reported as installed successfully. Restarted grafana and whenever it attempts to send an email alert notification, the image is missing from the email...

The following is output to the log...

```
...
...
t=2019-10-30T16:44:22+0800 lvl=info msg="Registering plugin" logger=plugins name="Grafana Image Renderer"
...
...
t=2019-10-30T16:44:22+0800 lvl=info msg="Renderer plugin found, starting" logger=rendering cmd=plugin_start_linux_amd64
...
...
t=2019-10-30T16:47:20+0800 lvl=info msg="New state change" logger=alerting.resultHandler ruleId=5 newState=pending prev state=ok
t=2019-10-30T16:52:40+0800 lvl=info msg="New state change" logger=alerting.resultHandler ruleId=5 newState=alerting prev state=pending
t=2019-10-30T16:52:40+0800 lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="Rendering failed: Error: Failed to launch chrome!\n/var/lib/grafana/plugins/grafana-image-renderer/chrome-linux/chrome: error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory\n\n\nTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md\n"
t=2019-10-30T16:52:40+0800 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses=[EMAIL]

```

Looks like the official grafana docker image does not have the dependencies required for the official grafana-image-renderer plugin?

Thanks,

**Comment by scharissis** [comment]
To anyone still experiencing this issue, note that we managed to "fix" it by NOT installing `grafana-image-renderer`.
That is, it seems that this package does the exact opposite of what it's meant to! :rofl:

**Comment by derN3rd** [comment]
As the error says, it's missing some libraries to start chrome. 
> `error while loading shared libraries: libX11.so[...]`

Running `ldd /var/lib/grafana/plugins/grafana-image-renderer/chrome-linux/chrome | grep not` shows me a list of missing libraries, which chrome requires. Shouldn't these be bundled by the plugin/chrome-headless?

Ubuntu 16.04.6 LTS
Running on AWS

Missing libs:
```
	libX11-xcb.so.1 => not found
	libXcomposite.so.1 => not found
	libXcursor.so.1 => not found
	libXdamage.so.1 => not found
	libXi.so.6 => not found
	libXtst.so.6 => not found
	libnss3.so => not found
	libnssutil3.so => not found
	libsmime3.so => not found
	libnspr4.so => not found
	libcups.so.2 => not found
	libXss.so.1 => not found
	libXrandr.so.2 => not found
	libasound.so.2 => not found
	libpangocairo-1.0.so.0 => not found
	libpango-1.0.so.0 => not found
	libcairo.so.2 => not found
	libatk-1.0.so.0 => not found
	libatk-bridge-2.0.so.0 => not found
	libgtk-3.so.0 => not found
	libgdk-3.so.0 => not found
	libgdk_pixbuf-2.0.so.0 => not found
```

**Comment by marefr** [comment]
For all of you already running Grafana in a docker container we suggest that you run the image renderer in a separate docker container, see https://github.com/grafana/grafana-image-renderer/blob/master/docs/remote_rendering_using_docker.md. 

We're planning to add some better documentation regarding this and instructions for how you can extend Grafana docker image to build a custom docker image to support installing the image renderer as a plugin.

**Comment by n1nj4888** [comment]
Given the previous PhantomJS renderer used to be part of the official grafana Docker image but is now/will be deprecated, would it be possible to include the new grafana-image-renderer in the official grafana Docker image, perhaps enabling its use through Docker container Environment Variables?

**Comment by marefr** [comment]
If you already run Grafana in docker container we suggests you run the image renderer in a separate docker container. 

[Readme](https://github.com/grafana/grafana-image-renderer/blob/master/README.md) updated together with [Grafana Image Rendering documentation](https://grafana.com/docs/administration/image_rendering/#grafana-image-renderer-plugin) and includes instructions for how to install the plugin in Grafana docker container..
