### ISSUE TITLE
Image renderer hangs if API responds with status code not equal to 200.

### ISSUE THREAD

**Issue by badrishroff** [grafana/grafana-image-renderer#435]
Below is the configuration we are using - 

```json
 "rendering": {
    "args": ["--no-sandbox", "--disable-gpu"],
    "ignoresHttpsErrors": false,
    "mode": "clustered",
    "clustering": {
      "mode": "context",
      "maxConcurrency": 5,
      "timeout": 120
    }
  }
```

Basically, we have increased the timeout to 120 seconds for the API request to complete. But as the API call failed with status code 401 the page hangs forever and will not allow other requests to complete. Also, observed `Browser uncaught exception` in the image renderer logs.

**Comment by alirezamansoori** [comment]
any updates on this?

**Comment by AgnesToulet** [comment]
Hello! Thanks for reporting this. What do you mean by "API request"? The Grafana data request for the panel you're trying to render? Would it be possible to provide the image renderer logs for the image renderer request that is failing? (Please enable [verbose logging](https://github.com/grafana/grafana-image-renderer/blob/master/dev.json#L51) and set [the logs level to debug](https://github.com/grafana/grafana-image-renderer/blob/master/dev.json#L13) before sharing your logs).

**Comment by AgnesToulet** [comment]
Closing this as stale. Please feel free to re-open if you have more information to share on this issue.
