### ISSUE TITLE
Failed to load resource: the server responded with a status of 403 (Forbidden)

### ISSUE THREAD

**Issue by ziyedbe** [grafana/grafana-image-renderer#437]
**What happened**:
`
[grafana-image-renderer] | {"level":"error","message":"Browser console error","msg":"Failed to load resource: the server responded with a status of 403 (Forbidden)","url":"http://IPADDRESS:3000/d-solo/qoUx89xMk/home-erp?orgId=1&from=1688550222167&to=1688636622167&panelId=69&width=1000&height=500&tz=Europe%2FParis&render=1"}
`
**How to reproduce it (as minimally and precisely as possible)**:
- Install grafana on server 1 (without Docker)
- install grafana image renderer on server 2 (With docker)

**Environment**: 
- Grafana Image Renderer version: 3.5.0
- Grafana version: v7.5.11
- Installed plugin or remote renderer service: remote renderer service on a docker container

**Comment by Clarity-89** [comment]
This is more likely the issue with your setup than the image renderer. To start debugging, you can check if you can access `http://IPADDRESS:3000/d-solo/qoUx89xMk/home-erp?orgId=1&from=1688550222167&to=1688636622167&panelId=69&width=1000&height=500&tz=Europe%2FParis&render=1` locally in your browser.

**Comment by AgnesToulet** [comment]
Closing this as stale. Please feel free to re-open if you tried the above and it's working.
