### ISSUE TITLE
Improve Rendering Times

### ISSUE THREAD

**Issue by jimmybrancaccio** [grafana/grafana-image-renderer#44]
Currently it takes my system about 12 seconds to render a graph image. Previous to installing this plugin it took about 2 seconds. I understand we likely can't get it back down to 2 seconds as more is involved with the plugin, but getting it down under double digits, preferably sub-5 seconds would be awesome.

**Comment by marefr** [comment]
@jimmybrancaccio thanks. Doesn't take 12 seconds for me. Think you can provide some more details about the system which you run Grafana and the image renderer plugin on like cpu, memory available together with [debug logs](https://github.com/grafana/grafana-image-renderer#troubleshooting) from Grafana server logs?

Also, what kind of panel/data are you rendering? How long does it take you to load it in browser until it has completely loaded? Maybe include dashboard or panel json may help.

**Comment by jimmybrancaccio** [comment]
Hey @marefr, here's some details on the server:

CPU: 1x Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz
RAM Available: 252MB

Nothing comes up in the Grafana logs. I had actually left it on the suggested value from when I was troubleshooting the other issue I had (in #41).

It doesn't matter what the panel data is, it happens on all my panels. It generally takes about 5-12 seconds to finish loading the entire thing.

That said, I'm curious how long it takes you to render something simple like CPU load or ethernet input/output.

![cypress-tx](https://user-images.githubusercontent.com/405585/66329378-041a2f80-e8f4-11e9-83ff-92ac0735f94c.png)

![server1-linuxbox-ninja](https://user-images.githubusercontent.com/405585/66329383-05e3f300-e8f4-11e9-84d8-6d2606ab5d5d.png)

Just a couple examples of what I'm rendering.

**Comment by marefr** [comment]
@jimmybrancaccio thanks. 

> Previous to installing this plugin it took about 2 seconds
- What exactly do you mean by this. When/how/what version did you install previously? 
- Are you installing it as a plugin in Grafana or running docker container?

Using Grafana test datasource (builtin) with `router_logging = true` in Grafana config and the following panel
![image](https://user-images.githubusercontent.com/1668778/68817382-d1492100-0681-11ea-9c78-f29b603a98d2.png)

```
Remote renderer in docker container:
INFO[11-14|01:44:30] Request Completed                        logger=context userId=1 orgId=1 uname=admin method=GET path=/render/d-solo/t29itP1Wz/render-locale-format status=200 remote_addr=[::1] time_ms=2227 size=97582 referer="http://localhost:3000/d/t29itP1Wz/render-locale-format?orgId=1&from=now-12h&to=now"
INFO[11-14|01:44:55] Request Completed                        logger=context userId=1 orgId=1 uname=admin method=GET path=/render/d-solo/t29itP1Wz/render-locale-format status=200 remote_addr=[::1] time_ms=2057 size=85358 referer="http://localhost:3000/d/t29itP1Wz/render-locale-format?orgId=1&from=now-12h&to=now"
INFO[11-14|01:44:58] Request Completed                        logger=context userId=1 orgId=1 uname=admin method=GET path=/render/d-solo/t29itP1Wz/render-locale-format status=200 remote_addr=[::1] time_ms=2214 size=100996 referer="http://localhost:3000/d/t29itP1Wz/render-locale-format?orgId=1&from=now-12h&to=now"

As plugin:
INFO[11-14|01:59:22] Request Completed                        logger=context userId=1 orgId=1 uname=admin method=GET path=/render/d-solo/t29itP1Wz/render-locale-format status=200 remote_addr=[::1] time_ms=1916 size=84977 referer="http://localhost:3000/d/t29itP1Wz/render-locale-format?orgId=1&from=now-12h&to=now"
INFO[11-14|02:00:22] Request Completed                        logger=context userId=1 orgId=1 uname=admin method=GET path=/render/d-solo/t29itP1Wz/render-locale-format status=200 remote_addr=[::1] time_ms=1931 size=101366 referer="http://localhost:3000/d/t29itP1Wz/render-locale-format?orgId=1&from=now-12h&to=now"
INFO[11-14|02:01:00] Request Completed                        logger=context userId=1 orgId=1 uname=admin method=GET path=/render/d-solo/t29itP1Wz/render-locale-format status=200 remote_addr=[::1] time_ms=1777 size=84536 referer="http://localhost:3000/d/t29itP1Wz/render-locale-format?orgId=1&from=now-12h&to=now"
```

Result: Average 2s per request for both running in docker and as a plugin

Based on that you only have 252MB available memory I think that could be a problem. Try to increase that if possible, or try to run remote renderer in docker container and limit the amount of resources container may use.

**Comment by marefr** [comment]
Closing this due to lack of response. We'll consider reopen the issue if you provide more information.
