### ISSUE TITLE
Feature request: Expose version over an API endpoint

### ISSUE THREAD

**Issue by theS1LV3R** [grafana/grafana-image-renderer#445]
**What would you like to be added**:

Projects like Grafana, Prometheus, Mimir, etc expose build and version info over API endpoints. It would be nice if grafana-image-renderer also did.

**Why is this needed**:

I run grafana-image-renderer in docker, and i use https://release-argus.io for monitoring updates for everything i host. Being able to check the version of the image renderer would allow me to check the version of it and be alerted on updates.

**Comment by Clarity-89** [comment]
There's `/render/version` endpoint where you can get the current version of the plugin.
