### ISSUE TITLE
User locale is not used when render image 

### ISSUE THREAD

**Issue by sanchomuzax** [grafana/grafana-image-renderer#45]
How can I change the format of numbers on Graphs?

The rendered image is:

![image](https://user-images.githubusercontent.com/2911588/66605513-89316d00-ebb0-11e9-8d9c-236df44fc656.png)

The browser version is:

![image](https://user-images.githubusercontent.com/2911588/66605575-9baba680-ebb0-11e9-8dc8-7cbba3d5bfb0.png)

How can I render it as a browser version?

**Comment by marefr** [comment]
@sanchomuzax Looks like a language/locale issue. What unit are you using in graph panel for the Y axis,  `locale format`? 

What languages have you configured in your browser, when I inspect a http request in network tab using chrome developer tools I see this request header `Accept-Language: sv,en-US;q=0.9,en;q=0.8` and when I use `locale format`.

Tested running both with a local Grafana instance and installed plugin and with a local Grafana instance with grafana-image-renderer container running on the same host as Grafana.

Can you provide more information about your setup?

**Comment by sanchomuzax** [comment]
> @sanchomuzax Looks like a language/locale issue. What unit are you using in graph panel for the Y axis, `locale format`?

![image](https://user-images.githubusercontent.com/2911588/72603250-f45dae80-3918-11ea-8d47-70c7067be314.png)

> What languages have you configured in your browser, when I inspect a http request in network tab using chrome developer tools I see this request header `Accept-Language: sv,en-US;q=0.9,en;q=0.8` and when I use `locale format`.

The language setting of Chrome on Windows desktop client side is Hungarian.

How could I configure of the language of the server side Chrome on CentOS for Grafana image renderer? I can't found it.

Could you help me? Tnx!

**Comment by marefr** [comment]
When you do panel -> share -> direct link rendered image you should get the browser timezone included at the end of the url `&tz=Europe%2FStockholm` and that is sent to the image render which should use that time zone to render.

**Comment by DanCech** [comment]
My understanding is that the timezone and the locale settings are different, to support this we'd need to also send the locale across.

**Comment by sanchomuzax** [comment]
> When you do panel -> share -> direct link rendered image you should get the browser timezone included at the end of the url `&tz=Europe%2FStockholm` and that is sent to the image render which should use that time zone to render.

~~~
&tz=Europe%2FBudapest
~~~

**Comment by sanchomuzax** [comment]
> My understanding is that the timezone and the locale settings are different, to support this we'd need to also send the locale across.

Where could I found this?

**Comment by sanchomuzax** [comment]
Thank you!

**Comment by marefr** [comment]
@sanchomuzax to fix this we need to make changes both in here and in Grafana. I wonder if a first step could be to add support for setting a default locale for the plugin or service through environment variable?
