### ISSUE TITLE
[3.8.1] - Crashloops - chrome_crashpad_handler: --database is required

### ISSUE THREAD

**Issue by trexx** [grafana/grafana-image-renderer#458]
**What happened**:
grafana-image-render 3.8.1 displays an error and crash loops on our Kubernetes cluster.

**What you expected to happen**:
That it behaves more like 3.7.2 and doesn't crashloop

**How to reproduce it (as minimally and precisely as possible)**:
Installed using Grafana helm chart version:  6.52.9

```yaml
imageRenderer:
  image:
    tag: 3.8.1
  enabled: true
  replicas: 1
  env:
    BROWSER_TZ: Europe/Copenhagen
    RENDERING_MODE: reusable
    HTTP_HOST: "0.0.0.0"
  serviceMonitor:
    enabled: true
    labels:
      prometheus: kube-prometheus-stack
  networkPolicy:
    limitIngress: true
    limitEgress: false
    extraIngressSelectors:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-prometheus-stack
```

**Anything else we need to know?**:

```json
{
  "@level": "error",
  "@message": "failed to start grafana-image-renderer",
  "error": "Failed to launch the browser process!\nchrome_crashpad_handler: --database is required\nTry 'chrome_crashpad_handler --help' for more information.\n[23:23:0919/092056.156243:ERROR:socket.cc(120)] recvmsg: Connection reset by peer (104)\n\n\nTROUBLESHOOTING: https://pptr.dev/troubleshooting\n",
  "trace": "Error: Failed to launch the browser process!\nchrome_crashpad_handler: --database is required\nTry 'chrome_crashpad_handler --help' for more information.\n[23:23:0919/092056.156243:ERROR:socket.cc(120)] recvmsg: Connection reset by peer (104)\n\n\nTROUBLESHOOTING: https://pptr.dev/troubleshooting\n\n    at Interface.onClose (/usr/src/app/node_modules/puppeteer-core/node_modules/@puppeteer/browsers/lib/cjs/launch.js:277:24)\n    at Interface.emit (node:events:525:35)\n    at Interface.close (node:readline:590:8)\n    at Socket.onend (node:readline:280:10)\n    at Socket.emit (node:events:525:35)\n    at endReadableNT (node:internal/streams/readable:1358:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"
}
```

**Environment**:
- Grafana Image Renderer version: 3.8.1
- Grafana version: 10.1.2
- Installed plugin or remote renderer service: remote renderer service
- OS Grafana Image Renderer is installed on: K3s v1.23.8+k3s2
- User OS & Browser: N/A
- Others: N/A

**Comment by AgnesToulet** [comment]
Hello! Thanks for reporting this. The `reusable` setting for `RENDERING_MODE` is experimental and not recommended. Could you try setting this to `default` (use less resources but rendering will be less performant) or `clustered` (use more resources as it opens multiple browsers in parallel but rendering will be more performant)? Also, could you set your log level to "debug" (using the LOG_LEVEL env variable) to see if you get more logs please? Thanks!

**Comment by trexx** [comment]
Hi there, here are some logs.

Clustered:
```json
{"level":"error","message":"Failed to get browser version"}
{"level":"debug","message":"Launching Browser cluster with puppeteer-cluster"}
```

Default:
```json
{"level":"error","message":"Failed to get browser version"}
```

**Comment by AgnesToulet** [comment]
Thank you. Yes, I think I found something. We are planning to do some more internal testing before releasing it. If you want to test it out yourself though, a Docker image containing the fix has been created (grafana/grafana-image-renderer:master-12c8779).

**Comment by trexx** [comment]
Thanks. FWIW, we're running it in our own test environment seems to start successfully.
