### ISSUE TITLE
ppc64le support

### ISSUE THREAD

**Issue by flynn1973** [grafana/grafana-image-renderer#46]
i run my grafana stuff on Redhat ppc64le. as chromium eventually seems to land on ppc64le (https://www.phoronix.com/scan.php?page=news_item&px=Chrome-POWER-Landing), is there a chance to get support for ppc64le?

**Comment by marefr** [comment]
Not sure what it would require to get this working on ppc64le even if support for chromium is added. I'll leave this open and see if others are interested in this.

**Comment by flynn1973** [comment]
testet with last git clone...at least it built and server can be started. is chromium needed for tis thing to work?

root@lpgaixmgmtlx01:/root/go/dev/src/github.com/grafana/grafana-image-renderer>node build/app.js server --port=8081
{"level":"info","message":"HTTP Server started, listening at http://localhost:8081"}
{"level":"error","message":"Failed to get browser version"}

**Comment by marefr** [comment]
@flynn1973 yes chromium is needed

**Comment by flynn1973** [comment]
i built this damned chromium browser from source but i still get the error about getting the browser version?

````
root@lpgaixmgmtlx01:/root/go/dev/src/github.com/grafana/grafana-image-renderer>echo $GF_RENDERER_PLUGIN_CHROME_BIN
/scratch/chromium_build/chromium/src/out/Default/chrome
root@lpgaixmgmtlx01:/root/go/dev/src/github.com/grafana/grafana-image-renderer>/scratch/chromium_build/chromium/src/out/Default/chrome --version
Chromium 82.0.4051.0
root@lpgaixmgmtlx01:/root/go/dev/src/github.com/grafana/grafana-image-renderer>node build/app.js server --port=8081
{"level":"info","message":"HTTP Server started, listening at http://localhost:8081"}
{"level":"error","message":"Failed to get browser version"}
````

**Comment by flynn1973** [comment]
linking the ppc64le chrome build directory into the .local-chromium directory fixes the error message, 

````
root@lpgaixmgmtlx01:/root/go/dev/src/github.com/grafana/grafana-image-renderer>ln -s /scratch/chromium_build/chromium/src/out/Default/ node_modules/puppeteer/.local-chromium/linux-706915/chrome-linux
````


seems that the "GF_RENDERER_PLUGIN_CHROME_BIN" variable is useless.

**Comment by marefr** [comment]
@flynn1973 Using custom Chrome/Chromium binary when running remote rendering service (when you  run `node build/app.js server --port=8081`) you cannot use `GF_RENDERER_PLUGIN_CHROME_BIN`, you have to use `CHROME_BIN`. An example can be seen in the [Dockerfile](https://github.com/grafana/grafana-image-renderer/blob/master/Dockerfile#L3).

If you're interested of adding this to documentation, please open a PR with changes to https://github.com/grafana/grafana-image-renderer/blob/master/docs/remote_rendering_using_docker.md#environment-variables

**Comment by flynn1973** [comment]
good point, by setting PUPPETEER_EXECUTABLE_PATH="/scratch/chromium_build/chromium/src/out/Default/chrome", and rebuild, the right binary is used.

````
root@lpgaixmgmtlx01:/scratch/node/lib/node_modules>ps -ef | grep render
root     14115 14095  0 12:05 ?        00:00:00 /scratch/chromium_build/chromium/src/out/Default/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI,BlinkGenPropertyTrees --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --headless --hide-scrollbars --mute-audio about:blank --no-sandbox --remote-debugging-port=0 --user-data-dir=/tmp/puppeteer_dev_profile-Ad9lpe
root     14134 14117  0 12:05 ?        00:00:00 /scratch/chromium_build/chromium/src/out/Default/chrome --type=renderer --no-sandbox --allow-pre-commit-input --disable-background-timer-throttling --disable-breakpad --enable-automation --file-url-path-alias=/gen=/scratch/chromium_build/chromium/src/out/Default/gen --force-color-profile=srgb --remote-debugging-port=0 --use-gl=swiftshader-webgl --field-trial-handle=2405002950355201423,4662979297113552848,131072 --enable-features=NetworkService,NetworkServiceInProcess --disable-features=BlinkGenPropertyTrees,TranslateUI --lang=en-US --headless --lang=en-US --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=3 --shared-files=v8_snapshot_data:100
````

will try to assemble the significant parts for a pr.

i think this issue can be closed, because the plugin now builds fine on ppc64le, the main culprit is the chrome binary which is not grafanas business.
