### ISSUE TITLE
Browser: Switch to new headless mode

### ISSUE THREAD

**Issue by AgnesToulet** [grafana/grafana-image-renderer#460]
Chrome is releasing a [new headless](https://developer.chrome.com/articles/new-headless/) mode. It is currently known to have some issues including [one](https://github.com/puppeteer/puppeteer/issues/10829) that seems to make Chrome crash when using Kubernetes so we are [not using it](https://github.com/grafana/grafana-image-renderer/pull/459).

In the future though, the old headless mode will be removed and we will need to either switch to the new headless mode or to use different Chrome binaries that contain the old one.

**Comment by evictorero** [comment]
There was a change in the [strategy](https://developer.chrome.com/blog/chrome-headless-shell), we could continue using the old headless mode for performance.
I'm planning to add it as part of the upgrade to Puppeteer 22.
