### ISSUE TITLE
Error on plugin download on grafana.com

### ISSUE THREAD

**Issue by AndiKu** [grafana/grafana-image-renderer#47]
I tried to download the plugin from https://grafana.com/grafana/plugins/grafana-image-renderer/installation with alternative download link (https://grafana.com/api/plugins/grafana-image-renderer/versions/1.0.5/download) but get error message:
````
{
  "code": "BadRequest",
  "message": "Version 1.0.5 is not available for undefined-undefined"
}
````
I tried with various browsers and also with curl from Linux server with same result.

**Comment by marefr** [comment]
Thanks. Please download it here https://github.com/grafana/grafana-image-renderer/releases

**Comment by jinleileiking** [comment]
same + 1

**Comment by marefr** [comment]
You can now download from grafana.com
