### ISSUE TITLE
Dependencies needed

### ISSUE THREAD

**Issue by simonc6372** [grafana/grafana-image-renderer#49]
On a minimal Centos install, the dependencies needed for grafana-image-renderer are not installed by default, and it's very difficult to establish exactly what RPMs need installing to allow the headless chrome to run. 
Installing chrome from RPM pulled in the dependencies needed (listed below) but this should not be necessary. It's possible some of these are NOT needed when running headless too. 

libXcomposite
libXdamage
libXtst
cups
libXScrnSaver 
pango 
atk
 adwaita-cursor-theme         
 adwaita-icon-theme           
 at                           
 at-spi2-atk                  
 at-spi2-core                 
 cairo-gobject                
 colord-libs                  
 dconf                        
 desktop-file-utils           
 ed                           
 emacs-filesystem             
 gdk-pixbuf2                  
 glib-networking              
 gnutls                       
 gsettings-desktop-schemas    
 gtk-update-icon-cache        
 gtk3                         
 hicolor-icon-theme           
 jasper-libs                  
 json-glib                    
 libappindicator-gtk3         
 libdbusmenu                  
 libdbusmenu-gtk3             
 libepoxy                     
 liberation-fonts             
 liberation-narrow-fonts      
 liberation-sans-fonts        
 liberation-serif-fonts       
 libgusb                      
 libindicator-gtk3            
 libmodman                    
 libproxy                     
 libsoup                      
 libwayland-cursor            
 libwayland-egl               
 libxkbcommon                 
 m4                           
 mailx                        
 nettle                       
 patch                        
 psmisc                       
 redhat-lsb-core              
 redhat-lsb-submod-security   
 rest                         
 spax                         
 time                         
 trousers                     
 xdg-utils                    
 xkeyboard-config

**Comment by marefr** [comment]
Thanks. Will try to improve documentation regarding dependencies.

**Comment by marefr** [comment]
Have added above list to official Grafana documentation by https://github.com/grafana/grafana/pull/20492. Will update the documentation/readme in this repository as well soon. Will close this for now.
