### ISSUE TITLE
more explanation on the installation pls

### ISSUE THREAD

**Issue by alwashe** [grafana/grafana-image-renderer#5]
~Where is the PluginFolder?    There is no Info: http://docs.grafana.org/plugins/installation/~
Edit: /var/lib/grafana/plugins

~What is:~
```yarn install --pure-lockfile```
```yarn run build```

~do i execute them as they are? do i need sudo?~
~Edit: i think they need to be executed in the pluginfolder? do i have to create a subfolder for the Plugin?~
not working

**Comment by simPod** [comment]
You don't need sudo, it just installs dependencies and then builds actual dist files.
