### ISSUE TITLE
Error Loading plugin in Gafana 10.4.0

### ISSUE THREAD

**Issue by fatbasstard** [grafana/grafana-image-renderer#505]
Update our Grafana from `10.3.3` to `10.4.0` (not other changes) and now hitting the following error:

```
Error: ✗ *rendering.RenderingService run error: Unrecognized remote plugin message: 
Failed to read any lines from plugin's stdout
This usually means
the plugin was not compiled for this architecture,
the plugin is missing dynamic-link libraries necessary to run,
the plugin is not executable by this process due to file permissions, or
the plugin failed to negotiate the initial go-plugin protocol handshake
Additional notes about plugin:
Path: /var/lib/grafana-plugins/grafana-image-renderer/plugin_start_linux_amd64
Mode: -rwxr-xr-x
Owner: 472 [grafana] (current: 472 [grafana])
Group: 0 [root] (current: 0 [root])
ELF architecture: EM_X86_64 (current architecture: amd64)
```

Something changed in Grafana perhaps? 

See: https://github.com/grafana/grafana/blob/main/CHANGELOG.md#1040-2024-03-06

**Comment by AgnesToulet** [comment]
Hello! I could not reproduce with Grafana 10.4.0 and the grafana-image-renderer 3.10.0 on Ubuntu. 

Which version of the grafana-image-renderer are you using? How do you run Grafana (on which OS? Using kubernetes? Docker? If so, could you share your configuration file?)

**Comment by MujahidRashid** [comment]
I am also facing the same issue
Grafana version 10.3.3 running in portainer
Using this dockerfile to build the image
https://github.com/grafana/grafana/blob/main/packaging/docker/custom/Dockerfile

**Comment by fatbasstard** [comment]
> Hello! I could not reproduce with Grafana 10.4.0 and the grafana-image-renderer 3.10.0 on Ubuntu.
> 
> Which version of the grafana-image-renderer are you using? How do you run Grafana (on which OS? Using kubernetes? Docker? If so, could you share your configuration file?)

Same as @MujahidRashid basically. We build our custom Docker image like this:

```docker
FROM grafana/grafana:10.4.0

RUN grafana cli --pluginsDir "$GF_PATHS_PLUGINS" --pluginUrl "https://github.com/grafana/grafana-image-renderer/releases/latest/download/plugin-linux-x64-glibc-no-chromium.zip" plugins install grafana-image-renderer
```

**Comment by fatbasstard** [comment]
Update: Just build a new image with the latest Grafana (`10.4.1`) and the latest Image Renderer (`3.10.1`) in the hope that something is changed to resolve this.

No luck same error

**Comment by fatbasstard** [comment]
Testing/debugging this locally is unfortately not possible for me due to the fact that I cannot run it locally (Got an Apple M1) due to missing ARM support (https://github.com/grafana/grafana-image-renderer/issues/7)

**Comment by ckljohn** [comment]
The default image doesn't work for me either. Then I tried with the `-ubuntu` image and it works.

**Comment by FUSAKLA** [comment]
Having same issue with the custom-built Docker image from https://github.com/grafana/grafana/blob/main/packaging/docker/custom/Dockerfile

tried changing the base image to the `-ubuntu` variant as @ckljohn suggested, but the error was still the same :/

**Comment by chennin** [comment]
Hi, I am having the same problem. I had gotten behind, so I can say that in the 10.2 series, it worked in 10.2.4 and broke in 10.2.5. Yep, same release day as 10.4.0 and 10.3.4.

Here is the repro - working - sets  GRAFANA_VERSION=10.2.4

```bash
mkdir -p /tmp/work && cd /tmp/work && \
wget https://raw.githubusercontent.com/grafana/grafana/main/packaging/docker/custom/Dockerfile && \
docker build --build-arg GF_INSTALL_IMAGE_RENDERER_PLUGIN=true --build-arg GRAFANA_VERSION=10.2.4 -t grafana-plugin-test . < ./Dockerfile | tee log.txt && \
docker run --rm -e GF_LOG_LEVEL="debug" grafana-plugin-test | tee -a log.txt
```

Repro - broken - sets  GRAFANA_VERSION=10.2.5

```bash
mkdir -p /tmp/work && cd /tmp/work && \
wget https://raw.githubusercontent.com/grafana/grafana/main/packaging/docker/custom/Dockerfile && \
docker build --build-arg GF_INSTALL_IMAGE_RENDERER_PLUGIN=true --build-arg GRAFANA_VERSION=10.2.5 -t grafana-plugin-test . < ./Dockerfile | tee log.txt && \
docker run --rm -e GF_LOG_LEVEL="debug" grafana-plugin-test | tee -a log.txt
```

**Comment by fatbasstard** [comment]
@AgnesToulet It's not that blocking ATM that I'm changing the OS behind our Grafana setup. So we're waiting for the actual fix

**Comment by superopsdev** [comment]
> Hi @fatbasstard, I'll look into this. Would the `-ubuntu` image like [ckljohn](https://github.com/grafana/grafana-image-renderer/issues/505#issuecomment-2036778558) suggested unblock you from upgrading?

Hi， How can I download -Ubuntu images？

**Comment by aardbol** [comment]
Same problem here using the Grafana Helm chart and version 10.4.3. Using the `-ubuntu` container image tag makes it work

**Comment by chennin** [comment]
The above release fixes it for me. Thank you!

(changing the plugin install version to v3.10.5, the package to `plugin-alpine-x64-no-chromium.zip` , and Grafana to v10.2.7)

**Comment by AgnesToulet** [comment]
Hello! Yes, we released a new asset for Alpine. You can now run the following command to install the plugin on Alpine: 
```
        grafana-cli \
          --pluginsDir "$GF_PATHS_PLUGINS" \
          --pluginUrl https://github.com/grafana/grafana-image-renderer/releases/latest/download/plugin-alpine-x64-no-chromium.zip \
          plugins install grafana-image-renderer; \
```
I opened [a PR](https://github.com/grafana/grafana/pull/88223/files) to update the custom Dockerfile with this new Alpine version.

For now, we only released a `no-chromium` version. Please tell us if the chromium version is needed.
