### ISSUE TITLE
How to get png image thourgh grafana-image-renderer?

### ISSUE THREAD

**Issue by phillipyuan** [grafana/grafana-image-renderer#52]
I'm a freshman of grafana and I am trying to get the panel image in png format from remote server.
I have unzipped  and downloaded plugin-linux-x64-glibc.zip in grafna plugins path.
However, I still have no idea how to use grafana-image-renderer so as to get the png in remote sever.
Can someone give any advice  or tutorials?

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

For reference, see [Grafana Documentation](https://grafana.com/docs/administration/image_rendering/).
