### ISSUE TITLE
full page rendering fails, using the latest Grafana and grafana image renderer

### ISSUE THREAD

**Issue by amnonh** [grafana/grafana-image-renderer#538]
**What happened**:
I'm using Grafana 11.1.0 and Grafana Renderer 3.11.0. I'm using the following URL to a full dashboard:
http://localhost:3000/render/d/detailed-6-0?orgId=1&from=1719479066300&to=1719484258954&width=1600&height=-1

I get only the visible screen (e.g. no scrolling is done).

![image](https://github.com/grafana/grafana-image-renderer/assets/2118079/372dee61-878e-4acc-8f28-73d881f4c220)

**What you expected to happen**:
The entire dashboard would be displayed
**How to reproduce it (as minimally and precisely as possible)**:
Take a long enough dashboard and see that it does not scroll.

**Anything else we need to know?**:
It would also be nice not to show the left menu

**Environment**:
- Grafana Image Renderer version: 3.11.0
- Grafana version: 11.1.0
- Installed plugin or remote renderer service: remote renderer in a docker container
- OS Grafana Image Renderer is installed on: docker
- User OS & Browser: chrome, fedora
- Others:

**Comment by vincent-olivert-riera** [comment]
@amnonh , could you confirm if this is still broken in [3.11.1](https://github.com/grafana/grafana-image-renderer/releases/tag/v3.11.1) that was release a few hours ago?

**Comment by amnonh** [comment]
@vincent-olivert-riera unfortunately, it is still broken.

**Comment by AgnesToulet** [comment]
Hi! You should use the latest version of the image renderer (3.11.1) and set `&kiosk` in your URL to remove the left navigation section that messes up with the scroll behavior.

**Comment by amnonh** [comment]
@AgnesToulet Thank you! adding the ```kiosk``` with version 3.11.1 solved the issue!

**Comment by akama-aka** [comment]
@AgnesToulet is it also possible to remove everything else? So that just the graph is to see?
