### ISSUE TITLE
Grafana-Image-Renderer and DashboardScene : Panel with id Nan not found

### ISSUE THREAD

**Issue by rgarmyn** [grafana/grafana-image-renderer#539]
**What happened**:
When rendering a panel using the "Direct link rendered image", a blank image returns with " Panel with id NaN not found"

**What you expected to happen**:
A rendered image to show.

**How to reproduce it**:
 in grafana.ini set [feature_toggles] enable=dashboardScene

**Environment**:
- Grafana Image Renderer version: V3.11.0
- Grafana version: V11.1
- OS Grafana Image Renderer is installed on: Ubuntu: 22.04
- User OS & Browser: Windows11, firefox.

**Comment by AgnesToulet** [comment]
Hello! You should also set the `dashboardSceneSolo` feature toggle to make it work. There are several feature toggles around Scenes, but they should all be enabled by default for Grafana 11.2 in August.
