### ISSUE TITLE
Allow specifying bind address via env variable

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana-image-renderer#61]
Hi,

I would like to have a GF_RENDERER_PLUGIN_BIND_ADDRESS env variable to define the host/port the renderer plugin is listening to.

My issue is that I have isolated grafana servers, with isolated users. With only one instance getting the port, I am seeing lots of permissiond denied because they write the files to other user's directories.

**Comment by marefr** [comment]
I think this have been fixed by #87 so will close this. Will be included in v1.0.8 stable and by default assign a port that is not in use, see https://github.com/grafana/grafana-image-renderer#environment-variables for details.

Let me know if this isn't enough to close this issue.
