### ISSUE TITLE
GF_RENDERER_PLUGIN_IGNORE_HTTPS_ERRORS=true docs to cover RPM based install.

### ISSUE THREAD

**Issue by simonc6372** [grafana/grafana-image-renderer#64]
The docs for "Ignore HTTPS errors" indicate to use 
export GF_RENDERER_PLUGIN_IGNORE_HTTPS_ERRORS=true 
to set the variable. 
We should also recognize that many enterprises run grafana from RPM, so should mention somewhere to add this variable to /etc/sysconfig/grafana-server

**Comment by marefr** [comment]
I tried to make the documentation generic to be applicable for whatever distribution you run. "You can override certain settings by using environment variables and making sure that those are available for the Grafana process.". Given RPM we already mention environment variables there https://grafana.com/docs/grafana/latest/installation/rpm/#environment-file.

What do you say? Should I just skip the example and simply refer to ` GF_RENDERER_PLUGIN_IGNORE_HTTPS_ERRORS=true`?

**Comment by simonc6372** [comment]
*My* view is where we mention docker environment variables, we should also mention where our RPM install stores them. (maybe automatically some way ? ) but I guess until we get there, this would be OK.

**Comment by marefr** [comment]
This have been fixed by #84 so will close this. Will consider updating the
