### ISSUE TITLE
arm64 fails to build

### ISSUE THREAD

**Issue by MarkoBursic** [grafana/grafana-image-renderer#65]
If I set `make build_package ARCH=arm64` then I get error from Node.js that arm64 is unknown, but linux-arm64 is known. Then I invoked `make build_package ARCH=linux-arm64` and somewhere the arm64 got eaten and it is parsed like linux-armv6. Then it says: Not able to build for 'armv6' here, only for 'arm64'. 
OK, I understand, but how to tell him that I don't want `armv6`, rather `arm64`?

make build_package ARCH=linux-arm64
rm -rf build
./scripts/clean_target.sh linux-arm64
./node_modules/.bin/tsc
./scripts/package_target.sh linux-arm64
> pkg@4.3.8
> Fetching base Node.js binaries to PKG_CACHE_PATH
  fetched-v10.4.1-linux-armv6  [                    ] 1%
> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.5/uploaded-v2.5-node-v10.4.1-linux-armv6
> Asset not found by direct link:
  {"tag":"v2.5","name":"uploaded-v2.5-node-v10.4.1-linux-armv6"}
> Not found in GitHub releases:
  {"tag":"v2.5","name":"uploaded-v2.5-node-v10.4.1-linux-armv6"}
> Building base binary from source:
  built-v10.4.1-linux-armv6
> Error! Not able to build for 'armv6' here, only for 'arm64'
child_process.js:656
    throw err;
    ^

**Comment by marefr** [comment]
See https://github.com/grafana/grafana-image-renderer/blob/master/docs/package_plugin_as_single_executable.md

We don't officially support packaging for ARM, but see https://github.com/grafana/grafana-image-renderer/issues/7#issuecomment-546599598 where someone have managed to pull it off for the remote rendering service using docker at least. 

Probably need `make build_package ARCH=linux-armd64-glibc` and you probably/maybe need to be on arm architecture to build for arm.

**Comment by MarkoBursic** [comment]
Have seen all of them yet before. I do think, that your project is very good, it works on ARM on its basics without trouble, I am very impressed. There are tons of applications like IoT requiring just that what you have done here. These apps runs on cheap SBCs , mostly ARM.  Users way to 'hack' the build are very painful without any true strategy. ARM64 is a family that it will last for quite long time, IMO it is also more suitable target for your project then any other family.

**Comment by marefr** [comment]
@MarkoBursic just saying that we not currently support packaging of ARM-compatible packages, but based on feedback/upvotes this could be something we add in the future and/or accept contribution of.
