### ISSUE TITLE
Use a pool of browsers to execute render requests

### ISSUE THREAD

**Issue by DanCech** [grafana/grafana-image-renderer#66]
Currently a new chrome instance is launched for every render request, which introduces latency and the possibility of running out of memory if too many requests come in at once.

Originally this requirement was because there wasn't a way to set the timezone for a particular page in puppeteer, but that is now available: https://github.com/puppeteer/puppeteer/blob/v2.0.0/docs/api.md#pageemulatetimezonetimezoneid

I'd suggest using https://github.com/Vincit/tarn.js to manage the pool of puppeteer browser objects so that we can easily handle multiple requests by running up to `pool.max` chrome instances and queuing requests until an instance is available.

**Comment by marefr** [comment]
Or https://github.com/thomasdondorf/puppeteer-cluster

**Comment by DanCech** [comment]
Nice find! That looks like it would do pretty much exactly what we need, and the `CONCURRENCY_CONTEXT` option should allow us to process multiple requests in a single chromium instance.

**Comment by marefr** [comment]
@DanCech Looking at https://github.com/puppeteer/puppeteer/pull/4949 introducing `emulateTimezone` it mentions that "Blocked on a Chromium roll to v79.0.3923.0 (r699550) or later, though." which is a quite recent version so could be hard to support this maybe. In addition, we need to upgrade puppeteer to v2.0.0, not sure if that would cause any problems. But will look into this and try it out.

**Comment by DanCech** [comment]
It looks like we could let puppeteer install chromium itself rather than pre-installing from the alpine edge package, which in theory at least should be more reliable since it's going to download the same version the release was tested against.  If we go that route and update to 2.0.0 then the per-page timezone should hopefully Just Work.

**Comment by marefr** [comment]
@DanCech problem though is that the puppeteer cannot automatically download chromium for alpine, at least that didn't work before. But one alternative would be to add an ubuntu image as well and/or build a custom one.

**Comment by DanCech** [comment]
Aha, that is a problem then, since the alpine packaged version in edge right now is 78.0.3904.108-r0 https://pkgs.alpinelinux.org/package/edge/community/x86_64/chromium which seems to be the current stable release as that's the version in the ubuntu etc repos also.

**Comment by DanCech** [comment]
Looks like alpine now has 79.0.3945.88-r0 in 3.11 and in edge
