### ISSUE TITLE
Panels rendering timeout

### ISSUE THREAD

**Issue by Teajo** [grafana/grafana-image-renderer#67]
Hello everyone,

I experienced some troubles with grafana image renderer (same troubles with PhantomJS renderer). 
Some panels (like Clock, DrawIO, and some of my custom panels) are impossible to render (the timeout is always reached).

Some logs :
lvl=eror msg="Render request failed" logger=rendering url="http://localhost:3000/d-solo/ksSgva0Wz/main?orgId=1&from=1572495407183&to=1572500826087&panelId=27&width=1000&height=500&tz=Europe%2FParis&render=1" error=map[name:TimeoutError] timestamp=0001-01-01T00:00:00.000Z

Environment :
- Grafana Image Renderer version : 1.0.7
- Grafana version : 6.4.3
- Installed plugin or remote renderer service : installed plugin
- OS Grafana Image Renderer is installed on: Debian 9
- User OS & Browser: Windows, Chrome

Do you know how can I fix that ?

Thanks

**Comment by marefr** [comment]
Please include more information like 

```
**Environment**:
- Grafana Image Renderer version:
- Grafana version:
- Installed plugin or remote renderer service:
- OS Grafana Image Renderer is installed on:
- User OS & Browser:
- Others:
```

**Comment by Teajo** [comment]
Sorry I have updated my message with informations you need ! Thanks

**Comment by marefr** [comment]
- Does it work to render graph panel? 
- Would suggest trying an older version of the plugin, like 1.0.5 to start with - does that work?
- In case above doesn't work, can you include a Grafana dashboard json having one of the panels that you're having problems to render, please leave out any sensitive information.

Thanks

**Comment by Teajo** [comment]
- Yes it works correctly with graph panel
- Tested with 1.0.5 and same troubles
- The file is attached. It contains a dashboard json with an unique flowcharting panel.
[dashboard.txt](https://github.com/grafana/grafana-image-renderer/files/3954423/dashboard.txt)

Thanks

**Comment by marefr** [comment]
Confirmed bug. Could be a bug in flowchart panel

**Comment by marefr** [comment]
Think `this.renderingCompleted()` needs to be called here and/or when render is finished: https://github.com/algenty/grafana-flowcharting/blob/master/src/flowchart_ctrl.js#L71

Would suggest to open an issue in https://github.com/algenty/grafana-flowcharting

**Comment by algenty** [comment]
Hi @marefr,

I don't know this method, i'll try it in next version

**Comment by algenty** [comment]
For information, work in progress, i added this.renderingCompleted(), render function give a result but without colors ;
![chrome_yvn8vIxAqm](https://user-images.githubusercontent.com/47012725/77236432-ab4b0480-6bbe-11ea-8c13-62676e3d78f6.png)

**Comment by algenty** [comment]
Hi @Teajo 
comme on  https://github.com/grafana/grafana-image-renderer/issues/67
