### ISSUE TITLE
http 500 Error with image renderer Plugin

### ISSUE THREAD

**Issue by emtie** [grafana/grafana-image-renderer#77]
**What happened**:

Hello all, I am running Grafana and integrated dashboards into icingaweb2. But wenn I open a page in icingaweb2 the dashboard of grafana does not appear. In the grafana logs I find the following entries:

`Jan 03 10:27:24 grafana grafana-server[949]: t=2020-01-03T10:27:24+0000 lvl=eror msg="Rendering failed." logger=context userId=0 orgId=1 uname= error="rpc error: code = Canceled desc = context canceled"
Jan 03 10:27:24 grafana grafana-server[949]: t=2020-01-03T10:27:24+0000 lvl=eror msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/render/d-solo/ZK27sqXmz/icinga2-default status=500 remote_addr=10.x.x.x time_ms=4985 size=1722 referer=
Jan 03 10:27:44 grafana grafana-server[949]: t=2020-01-03T10:27:44+0000 lvl=eror msg="Render request failed" logger=rendering url="h2://localhost:3000/d-solo/ZK27sqXmz/icinga2-default?var-hostname=servername.local&var-service=ping4&var-command=ping4&panelId=1&orgId=1&width=640&height=280&theme=light&from=now-6h&to=now&render=1" error=map[name:TimeoutError] timestamp=0001-01-01T00:00:00.000Z`

When i click on the panel in icingaweb2 where the grafana dashboard should appear I immediatelly see the right dashboard...

**What you expected to happen**:
Dashboard would open up :-)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
I have installed Grafana via deb File und downloaded Grafana Image Renderer Version 1.0.7 via github und unzipped it in /var/lib/grafana/plugins and chmoded user to grafana:grafana afterward I checked ldd dependencies and they seemed to be fine...
`        linux-vdso.so.1 (0x00007ffd8d932000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f34b4a3c000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f34b481d000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f34b4615000)
        libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f34b42dd000)
        libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007f34b40db000)
        libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f34b3eb3000)
        libXcomposite.so.1 => /usr/lib/x86_64-linux-gnu/libXcomposite.so.1 (0x00007f34b3cb0000)
        libXcursor.so.1 => /usr/lib/x86_64-linux-gnu/libXcursor.so.1 (0x00007f34b3aa6000)
        libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007f34b38a3000)
        libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f34b3691000)
        libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007f34b348b000)
        libXi.so.6 => /usr/lib/x86_64-linux-gnu/libXi.so.6 (0x00007f34b327b000)
        libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f34b3071000)
        libXtst.so.6 => /usr/lib/x86_64-linux-gnu/libXtst.so.6 (0x00007f34b2e6b000)
        libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007f34b2c17000)
        libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f34b2900000)
        libnss3.so => /usr/lib/x86_64-linux-gnu/libnss3.so (0x00007f34b25bc000)
        libnssutil3.so => /usr/lib/x86_64-linux-gnu/libnssutil3.so (0x00007f34b238d000)
        libsmime3.so => /usr/lib/x86_64-linux-gnu/libsmime3.so (0x00007f34b2161000)
        libnspr4.so => /usr/lib/x86_64-linux-gnu/libnspr4.so (0x00007f34b1f24000)
        libcups.so.2 => /usr/lib/x86_64-linux-gnu/libcups.so.2 (0x00007f34b1c98000)
        libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f34b1a66000)
        libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007f34b1819000)
        libXss.so.1 => /usr/lib/x86_64-linux-gnu/libXss.so.1 (0x00007f34b1615000)
        libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f34b140e000)
        libXrandr.so.2 => /usr/lib/x86_64-linux-gnu/libXrandr.so.2 (0x00007f34b1203000)
        libgio-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007f34b0e64000)
        libasound.so.2 => /usr/lib/x86_64-linux-gnu/libasound.so.2 (0x00007f34b0b5d000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f34b07bf000)
        libpangocairo-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0 (0x00007f34b05b2000)
        libpango-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0 (0x00007f34b0365000)
        libcairo.so.2 => /usr/lib/x86_64-linux-gnu/libcairo.so.2 (0x00007f34b0048000)
        libatk-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0 (0x00007f34afe22000)
        libatk-bridge-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0 (0x00007f34afbf1000)
        libgtk-3.so.0 => /usr/lib/x86_64-linux-gnu/libgtk-3.so.0 (0x00007f34af2e9000)
        libgdk-3.so.0 => /usr/lib/x86_64-linux-gnu/libgdk-3.so.0 (0x00007f34aeff3000)
        libgdk_pixbuf-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0 (0x00007f34aedcf000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f34aebb7000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f34ae7c6000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f34bda30000)
        libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f34ae5c2000)
        libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f34ae3bc000)
        libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f34ae1b4000)
        libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f34adf42000)
        libplc4.so => /usr/lib/x86_64-linux-gnu/libplc4.so (0x00007f34add3d000)
        libplds4.so => /usr/lib/x86_64-linux-gnu/libplds4.so (0x00007f34adb39000)
        libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007f34ad8ee000)
        libgnutls.so.30 => /usr/lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007f34ad589000)
        libavahi-common.so.3 => /usr/lib/x86_64-linux-gnu/libavahi-common.so.3 (0x00007f34ad37d000)
        libavahi-client.so.3 => /usr/lib/x86_64-linux-gnu/libavahi-client.so.3 (0x00007f34ad16c000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f34acf4f000)
        libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007f34acccb000)
        libgmodule-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007f34acac7000)
        libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007f34ac89f000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f34ac684000)
        libmount.so.1 => /lib/x86_64-linux-gnu/libmount.so.1 (0x00007f34ac430000)
        libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f34ac1eb000)
        libpangoft2-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0 (0x00007f34abfd5000)
        libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f34abd21000)
        libthai.so.0 => /usr/lib/x86_64-linux-gnu/libthai.so.0 (0x00007f34abb18000)
        libpixman-1.so.0 => /usr/lib/x86_64-linux-gnu/libpixman-1.so.0 (0x00007f34ab873000)
        libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f34ab641000)
        libxcb-shm.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007f34ab43e000)
        libxcb-render.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007f34ab231000)
        libatspi.so.0 => /usr/lib/x86_64-linux-gnu/libatspi.so.0 (0x00007f34ab001000)
        libcairo-gobject.so.2 => /usr/lib/x86_64-linux-gnu/libcairo-gobject.so.2 (0x00007f34aadf8000)
        libepoxy.so.0 => /usr/lib/x86_64-linux-gnu/libepoxy.so.0 (0x00007f34aaaf7000)
        libXinerama.so.1 => /usr/lib/x86_64-linux-gnu/libXinerama.so.1 (0x00007f34aa8f4000)
        libxkbcommon.so.0 => /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0 (0x00007f34aa6b5000)
        libwayland-cursor.so.0 => /usr/lib/x86_64-linux-gnu/libwayland-cursor.so.0 (0x00007f34aa4ad000)
        libwayland-egl.so.1 => /usr/lib/x86_64-linux-gnu/libwayland-egl.so.1 (0x00007f34aa2ab000)
        libwayland-client.so.0 => /usr/lib/x86_64-linux-gnu/libwayland-client.so.0 (0x00007f34aa09c000)
        libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f34a9e87000)
        libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007f34a9bb1000)
        libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007f34a997f000)
        libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f34a977b000)
        libkrb5support.so.0 => /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007f34a9570000)
        libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007f34a9241000)
        libidn2.so.0 => /usr/lib/x86_64-linux-gnu/libidn2.so.0 (0x00007f34a9024000)
        libunistring.so.2 => /usr/lib/x86_64-linux-gnu/libunistring.so.2 (0x00007f34a8ca6000)
        libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007f34a8a93000)
        libnettle.so.6 => /usr/lib/x86_64-linux-gnu/libnettle.so.6 (0x00007f34a885d000)
        libhogweed.so.4 => /usr/lib/x86_64-linux-gnu/libhogweed.so.4 (0x00007f34a8629000)
        libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f34a83a8000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f34a8182000)
        liblz4.so.1 => /usr/lib/x86_64-linux-gnu/liblz4.so.1 (0x00007f34a7f66000)
        libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f34a7c4b000)
        libblkid.so.1 => /lib/x86_64-linux-gnu/libblkid.so.1 (0x00007f34a79fe000)
        libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007f34a7760000)
        libdatrie.so.1 => /usr/lib/x86_64-linux-gnu/libdatrie.so.1 (0x00007f34a7559000)
        libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007f34a7355000)
        libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f34a7140000)
        libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007f34a6f13000)`

grafana.ini
` [rendering]
# Options to configure a remote HTTP image rendering service, e.g. using https://github.com/grafana/grafana-image-renderer.
# URL to a remote HTTP image renderer service, e.g. http://localhost:8081/render, will enable Grafana to render panels and dashboards to PNG-images using HTTP requests to an external service.
;server_url =
# If the remote HTTP image renderer service runs on a different server than the Grafana server you may have to configure this to a URL where Grafana is reachable, e.g. http://grafana.domain/.
;callback_url =`

**Environment**:
- Grafana Image Renderer version: 1.0.7 (via plugin-linux-x64-glibc.zip)
- Grafana version: Grafana v6.5.2 (742d165) (via  https://dl.grafana.com/oss/release/grafana_6.5.2_amd64.deb)
- Installed plugin or remote renderer service: Grafana Image Renderer from https://github.com/grafana/grafana-image-renderer/releases/download/v1.0.7/plugin-linux-x64-glibc.zip
- OS Grafana Image Renderer is installed on: Ubuntu 18.04.3
- User OS & Browser: User OS Windows 10 Prof. & Firefox 71.0 x64
- Others:
``

**Comment by marefr** [comment]
I think this is the problem `url="h2://`. Quick workaround switch from http2 to https configuration temporarily. Will submit a patch for this to Grafana repository.
