### ISSUE TITLE
[May be a bug] The rows are not open automaticlly.

### ISSUE THREAD

**Issue by jinleileiking** [grafana/grafana-image-renderer#79]
When captured, the pic cannot open the show, the pic cannot show the visualizes in row.

**Comment by jinleileiking** [comment]
![image](https://user-images.githubusercontent.com/93968/71960281-90a7f700-322f-11ea-9203-4ac8465fbd79.png)

**Comment by marefr** [comment]
Rendering a full dashboard is experimental and you'll need to save the dashboard with row expanded for the renderer to be able to capture an image of it.
