### ISSUE TITLE
Grafana panel alert details cause failure

### ISSUE THREAD

**Issue by sdwire** [grafana/grafana-image-renderer#81]
Configured the grafana-image-renderer as a docker container with a sneaky datasource configuration problem that only affected the renderer, then tried to render an image

**What happened**:

Got a generic error message displayed in Grafana directing to logs for more info. Renderer logged a timeout error in waitForFunction() with no additional information.

**What you expected to happen**:

Expected either a) the Grafana data-retrieval error would be logged (which it wasn't) or b) the data-retrieval error that it rendered in the browser would be returned as a browser screenshot by the renderer. 

**How to reproduce it (as minimally and precisely as possible)**:

Define a Prometheus datasource in Grafana with the following characteristics:
- Configured to have the browser load the data rather than having Grafana proxy
- Use a hostname that can be resolved by the end user's browser, but not by containers in the docker host
- Try to have Grafana render an image of a panel based on that Prometheus datasource

**Anything else we need to know?**:

Changing browser.ts starting on line 66 as below allows the renderer to send back a screenshot of Grafana's error message, which allows troubleshooting to continue:

```
      // wait for all panels (or any alert panel) to render.
      await page.waitForFunction(
        () => {
          const panelCount = document.querySelectorAll('.panel').length || document.querySelectorAll('.panel-container').length;
          return ((window as any).panelsRendered >= panelCount) || (document.querySelectorAll('.alert').length > 0);
        },
        {
          timeout: options.timeout * 1000,
        }
      );
```

**Environment**:
- Grafana Image Renderer version:
- Grafana version:
- Installed plugin or remote renderer service:
- OS Grafana Image Renderer is installed on:
- User OS & Browser:
- Others:

**Comment by sdwire** [comment]
See https://github.com/grafana/grafana-image-renderer/pull/83 for proposed resolution

**Comment by marefr** [comment]
Please try v1.0.10 since that includes capture of console output.

**Comment by marefr** [comment]
Closing this due to lack of response. We'll consider reopen the issue if you provide more information.
