### ISSUE TITLE
How to debug TimeoutError

### ISSUE THREAD

**Issue by dnull88** [grafana/grafana-image-renderer#97]
Grafana and grafana-image-renderer run on AWS ECS. Communication over default docker interface (172.17.0.1), grafana is binded on 172.17.0.1:3000, renderer on 172.17.0.1:8082.
Rendering doesn't works (500 error, connection timeout): 

**Logs from rendering container:**
`(node:7) UnhandledPromiseRejectionWarning: TypeError: Bind must be called on a function
    at Page.bind (<anonymous>)
    at Page.emit (events.js:223:5)
    at Page._onTargetCrashed (/usr/src/app/node_modules/puppeteer/lib/Page.js:216:10)
    at CDPSession.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/Page.js:124:56)
    at CDPSession.emit (events.js:223:5)
    at CDPSession._onMessage (/usr/src/app/node_modules/puppeteer/lib/Connection.js:200:12)
    at Connection._onMessage (/usr/src/app/node_modules/puppeteer/lib/Connection.js:112:17)
    at WebSocket.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/WebSocketTransport.js:44:24)
    at WebSocket.onMessage (/usr/src/app/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:223:5)
(node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
{"url":"/render?domain=172.17.0.1&encoding=&height=500&renderKey=WxUKvd8vCd6S6PcYHRSqmlO7pjQPGnTA&timeout=15&timezone=&url=http%3A%2F%2F172.17.0.1%3A3000%2Fd-solo%2FmoLFi08Wz%2Ftest_dash%3ForgId%3D1%26panelId%3D2%26render%3D1&width=1000","stack":"TimeoutError: Navigation timeout of 30000 ms exceeded\n    at /usr/src/app/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21\n  -- ASYNC --\n    at Frame.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:111:15)\n    at Page.goto (/usr/src/app/node_modules/puppeteer/lib/Page.js:675:49)\n    at Page.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:112:23)\n    at Browser.<anonymous> (/usr/src/app/build/browser/browser.js:154:28)\n    at Generator.next (<anonymous>)\n    at /usr/src/app/build/browser/browser.js:7:71\n    at new Promise (<anonymous>)\n    at __awaiter (/usr/src/app/build/browser/browser.js:3:12)\n    at /usr/src/app/build/browser/browser.js:152:47\n    at NoOpBrowserTiming.<anonymous> (/usr/src/app/build/browser/browser.js:27:26)\n  -- ASYNC --\n    at Page.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:111:15)\n    at Browser.<anonymous> (/usr/src/app/build/browser/browser.js:154:28)\n    at Generator.next (<anonymous>)\n    at /usr/src/app/build/browser/browser.js:7:71\n    at new Promise (<anonymous>)\n    at __awaiter (/usr/src/app/build/browser/browser.js:3:12)\n    at /usr/src/app/build/browser/browser.js:152:47\n    at NoOpBrowserTiming.<anonymous> (/usr/src/app/build/browser/browser.js:27:26)\n    at Generator.next (<anonymous>)\n    at /usr/src/app/build/browser/browser.js:7:71","level":"error","message":"Request failed"}
`

**Logs from grafana:**
`t=2020-02-06T13:29:59+0000 lvl=eror msg="Failed to send request to remote rendering service." logger=rendering renderer=http error="Get http://172.17.0.1:8082/render?domain=172.17.0.1&encoding=&height=500&renderKey=WxUKvd8vCd6S6PcYHRSqmlO7pjQPGnTA&timeout=15&timezone=&url=http%3A%2F%2F172.17.0.1%3A3000%2Fd-solo%2FmoLFi08Wz%2Ftest_dash%3ForgId%3D1%26panelId%3D2%26render%3D1&width=1000: context deadline exceeded"
t=2020-02-06T13:29:59+0000 lvl=eror msg="Failed to render and upload alert panel image." logger=alerting.notifier ruleId=47 error="Failed to send request to remote rendering service. Get http://172.17.0.1:8082/render?domain=172.17.0.1&encoding=&height=500&renderKey=WxUKvd8vCd6S6PcYHRSqmlO7pjQPGnTA&timeout=15&timezone=&url=http%3A%2F%2F172.17.0.1%3A3000%2Fd-solo%2FmoLFi08Wz%2Ftest_dash%3ForgId%3D1%26panelId%3D2%26render%3D1&width=1000: context deadline exceeded"`

**Comment by marefr** [comment]
@dnull88 what Grafana version are you using?

**Comment by dnull88** [comment]
I'm using latest grafana and grafana-image-renderer docker images. Also tried grafana 6.6.0 - same error

**Comment by marefr** [comment]
Just released grafana-image-renderer v1.0.10. Please make sure that you're using docker image grafana/grafana:6.6.1 and grafana/grafana-image-renderer:1.0.10 to make sure that you're not using an older/cached version referring to latest. 

- Are you running one instance of Grafana or multiple? 
- How much CPU/memory do you have available for the image renderer container? 
- If you browse http://172.17.0.1:3000/d-solo/moLFi08Wz/test_dash?orgId=1&panelId=2 does that render what you expect and there's no errors logged in console (chrome dev tools)?
- Can you try browse http://172.17.0.1:3000/d-solo/moLFi08Wz/test_dash?orgId=1, panel context menu of panel with id 2, share and then Direct link rendered image since that will use a timeout of 30 seconds per default.
- Can you try increasing https://grafana.com/docs/grafana/latest/installation/configuration/#notification-timeout-seconds to something like 60, this will give image renderer 30 seconds to render an image. 
- Can you include dashboard json of http://172.17.0.1:3000/d-solo/moLFi08Wz/test_dash?orgId=1?

**Comment by marefr** [comment]
Forgot to mention that you since v1.0.9 can provide a configuration file where you can enable verbose logging which should log all the requests that headless browser are executing, see https://github.com/grafana/grafana-image-renderer/blob/master/docs/remote_rendering_using_docker.md#configuration-file.

Will consider making this configurable through environment variable.

**Comment by marefr** [comment]
v1.0.11 is released which enables you to enable verbose logging using environment variables. For docker/service see https://github.com/grafana/grafana-image-renderer/blob/master/docs/remote_rendering_using_docker.md#environment-variables. Please try enabling that and report back Grafana server log output. Thanks

**Comment by marefr** [comment]
Closing this due to lack of response. We'll consider reopen the issue if you provide more information.

**Comment by alertauser** [comment]
I'm facing the same problem with Image  Renderer Plugin version 2.0.0
Grafana v7.2.0

Increasing the notification_timeout_seconds did not have any effect, the operation times out after 30 secs.

CONFIGURATION:
---------------
[server]
http_addr = myhost-grafana-1.monitoring.mydomain.net

[alerting]
enabled = true
notification_timeout_seconds = 60
concurrent_render_limit = 10

[rendering]
LOG_LEVEL = debug

LOGS:
-----
`Oct 06 13:34:00 myhost-grafana-1.openstacklocal grafana-server[9565]: t=2020-10-06T13:34:00+0000 lvl=info msg=Rendering logger=rendering renderer=plugin path="d-solo/kmlbhWpg/business-kpi-billable-vsgs?orgId=1&from=1601769600000&to=1601855999999&var-interval=$__auto_interval_interval&var-datasource=victoria-cluster-prod&var-rate_period=5m&var-billable=All&var-VSG_FQDN=All&panelId=145&width=1000&height=500&tz=America%2FNew_York"

Oct 06 13:34:00 myhost-grafana-1.openstacklocal grafana-server[9565]: t=2020-10-06T13:34:00+0000 lvl=dbug msg="Calling renderer plugin" logger=rendering renderer=plugin req="url:\"https://myhost-grafana-1.monitoring.mydomain.net:3000/d-solo/kmlbhWpg/business-kpi-billable-vsgs?orgId=1&from=1601769600000&to=1601855999999&var-interval=$__auto_interval_interval&var-datasource=victoria-cluster-prod&var-rate_period=5m&var-billable=All&var-VSG_FQDN=All&panelId=145&width=1000&height=500&tz=America%2FNew_York&render=1\" width:1000 height:500 deviceScaleFactor:1 filePath:\"/var/lib/grafana/png/kCUdphx3USFDufXTASsh.png\" renderKey:\"EtoIuKntiKFH3qdwwC8uGO2vRUfCujaY\" domain:\"myhost-grafana-1.monitoring.mydomain.net\" timeout:60 timezone:\"America/New_York\" headers:<key:\"Accept-Language\" value:<values:\"en-US,en;q=0.9\" > > "

Oct 06 13:34:30 myhost-grafana-1.openstacklocal grafana-server[9565]: t=2020-10-06T13:34:30+0000 lvl=eror msg="Render request failed" logger=plugins.backend pluginId=grafana-image-renderer url="https://myhost-grafana-1.monitoring.mydomain.net:3000/d-solo/kmlbhWpg/business-kpi-billable-vsgs?orgId=1&from=1601769600000&to=1601855999999&var-interval=$__auto_interval_interval&var-datasource=victoria-cluster-prod&var-rate_period=5m&var-billable=All&var-VSG_FQDN=All&panelId=145&width=1000&height=500&tz=America%2FNew_York&render=1" error="TimeoutError: Navigation timeout of 30000 ms exceeded"

Oct 06 13:34:30 myhost-grafana-1.openstacklocal grafana-server[9565]: t=2020-10-06T13:34:30+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=myname method=GET path=/render/d-solo/kmlbhWpg/business-kpi-billable-vsgs status=500 remote_addr=10.166.58.148 time_ms=30235 size=714 referer="https://myhost-grafana-1.monitoring.mydomain.net:3000/d/kmlbhWpg/business-kpi-billable-vsgs?orgId=1"
`

**Comment by alertauser** [comment]
> Closing this due to lack of response. We'll consider reopen the issue if you provide more information.



> Closing this due to lack of response. We'll consider reopen the issue if you provide more information.

I'm having the same problem. Gave more info in the comment.
